### ISSUE TITLE
Pytorch snapshot unsatisfied link error org.bytedeco.pytorch.global.torch.IR_VERSION

### ISSUE THREAD

**Issue by guangster** [bytedeco/javacpp-presets#1076]
Hi, pytorch javacpp-presets works fine if we use 1.9.0-1.5.6, however, on the latest 1.9.0-1.5.7-SNAPSHOT version, the same Java code gave me this error. Any help is greatly appreciated.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.pytorch.global.torch.IR_VERSION()J
	at org.bytedeco.pytorch.global.torch.IR_VERSION(Native Method)
	at org.bytedeco.pytorch.global.torch.<clinit>(torch.java:17716)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1212)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
	at org.bytedeco.pytorch.Module.<clinit>(Module.java:63)
	at recsys2021.nnDJL.DJLJavaCPPUtils.getModelCPP(DJLJavaCPPUtils.java:21)
	at recsys2021.nnDJL.DJLJavaCPPUtils.main(DJLJavaCPPUtils.java:51)```

**Comment by saudet** [comment]
I'm not sure where this is coming from, it works fine for me on both Linux and Windows, but they don't look like important constants, so let's just skip those I guess. On which platform are you getting that BTW?

**Comment by guangster** [comment]
ubuntu 20.04.
how do I skip this?

**Comment by saudet** [comment]
By adding them to an Info.skip() list like this one:
https://github.com/bytedeco/javacpp-presets/blob/master/pytorch/src/main/java/org/bytedeco/pytorch/presets/torch.java#L872

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacpp-presets/commit/ded739e5d93525ec5e3c3a84b236df7fc121b9e8. Thanks for reporting!
