### ISSUE TITLE
no jniavutil in java.library.path

### ISSUE THREAD

**Issue by nkligang** [bytedeco/javacpp-presets#1084]
Hi, I am just trying to run the sample code in README but it is not working. 
```
Read few frame and write to image
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1738)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1345)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
	at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1212)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
	at org.bytedeco.ffmpeg.avformat.AVFormatContext.<clinit>(AVFormatContext.java:36)
	at com.fenglinga.javacpp.ReadFewFrame.main(ReadFewFrame.java:48)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniavutil in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1705)
	... 11 more
```

My pom.xml file is
```
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.bytedeco.ffmpeg</groupId>
    <artifactId>readfewframe</artifactId>
    <version>1.5.6</version>
    <properties>
        <exec.mainClass>ReadFewFrame</exec.mainClass>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>
    </dependencies>
</project>
```

But I tried use jars download 'javacpp-presets-platform-1.5.6-bin' from release, It's works! how?

**Comment by saudet** [comment]
Probably just a buggy version of Maven? Please upgrade to the latest version.

**Comment by nkligang** [comment]
> Probably just a buggy version of Maven? Please upgrade to the latest version.

the version of 1.3.2-1.5.5 works

```
	<dependency>
		<groupId>org.bytedeco</groupId>
		<artifactId>ffmpeg-platform</artifactId>
		<version>4.3.2-1.5.5</version>
	</dependency>
	<dependency>
		<groupId>org.bytedeco</groupId>
		<artifactId>ffmpeg-platform-gpl</artifactId>
		<version>4.3.2-1.5.5</version>
	</dependency>
```

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to
"true" to get more information about loading failures.

**Comment by nkligang** [comment]
when I clear 'C:\Users\Administrator\.m2\repository\org\bytedeco'，rebuild，and it is works, thank you. I think this problem is some jar maybe download failed.
