### ISSUE TITLE
pytorch binding use libtorch with cuda 11.1

### ISSUE THREAD

**Issue by scott01272001** [bytedeco/javacpp-presets#1105]
Hi, I'm using the 1.5.7 PyTorch binding and I need to use libtorch with cuda version 11.1 and I followed the advice in the issue [#1083](https://github.com/bytedeco/javacpp-presets/issues/1083) to extract the library to /usr/lib also set the "org.bytedeco.javacpp.pathsFirst" system property to "true", after that, my program shows the error below:

java.lang.UnsatisfiedLinkError: no jnitorch in java.library.path
...
Caused by: java.lang.UnsatisfiedLinkError: /home/appuser/.javacpp/cache/fast-reid-java.jar/org/bytedeco/pytorch/linux-x86_64/libjnitorch.so: /home/appuser/.javacpp/cache/fast-reid-java.jar/org/bytedeco/pytorch/linux-x86_64/libjnitorch.so: undefined symbol: _ZN5torch2nn17ReflectionPadImplILm3ENS0_19ReflectionPad3dImplEE5resetEv
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
at java.lang.Runtime.load0(Runtime.java:810)
at java.lang.System.load(System.java:1088)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1709)`

do I miss something important?

thank you

**Comment by saudet** [comment]
The versions of PyTorch need to match.

**Comment by scott01272001** [comment]
Thanks for the comment, my PyTorch version is 1.8.2 and I install the corresponding version of libtorch but still didn't work, or do you mean I should use the PyTorch version corresponding to 1.5.7 Pytorch preset? 
If so, is it possible to use cuda 11.1 with 1.5.7?

thanks a lot

**Comment by saudet** [comment]
There are no presets available for 1.8.x. The oldest version supported is 1.9.0:
https://repo1.maven.org/maven2/org/bytedeco/pytorch/
Is there a reason you cannot upgrade your version of PyTorch?

**Comment by scott01272001** [comment]
Hi saudet, thank you, I have solved the problem by upgrading the PyTorch version to 1.10.1 with Cuda 11.1 support, thanks again.
