### ISSUE TITLE
Linux libjniavutil.so linking against libX11.so.6 for some reason (in ffmpeg 5.0-1.5.7-SNAPSHOT)

### ISSUE THREAD

**Issue by jfehr67** [bytedeco/javacpp-presets#1142]
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-linux-x86_64-gpl.jar/org/bytedeco/ffmpeg/linux-x86_64-gpl/libjniavutil.so: libX11.so.6: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)

I have a feeling this is the same issue that happened with macos, but I'm not sure if there's something special about the linux version that requires X11? If not, I can put in a PR to add the same flags.

I notice though that some of the linux builds have --enable-libxcb and some don't. Is this intentional? Is it ok to remove it? The older versions of ffmpeg didn't link with libX11, as far as I can tell.

**Comment by saudet** [comment]
This has been fixed. Please stop opening duplicate issues.

**Comment by jfehr67** [comment]
I just pulled the latest, and I don't see any changes for the linux builds. (only the macos ones) Am I missing something?

**Comment by saudet** [comment]
Duplicate of #1136

**Comment by saudet** [comment]
We can open new issues for every little detail, but this is pretty much the same issue. It just makes it more difficult to follow the same discussion in multiple threads. There's no benefit. Also, we don't need to open an issue before opening a pull request! If you have an idea of how to fix it, please open a pull request without opening an issue. There's no point in duplicating everything all over the place.
