### ISSUE TITLE
UnsatisfiedLinkError: no jniopencv_dnn in java.library.path

### ISSUE THREAD

**Issue by targit007** [bytedeco/javacpp-presets#1316]
Env: Windows 64 Bit

JavaCV: 

> <dependencies>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.8</version>
        </dependency>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform-gpu</artifactId>
            <version>4.6.0-1.5.8</version>
        </dependency>

        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>5.1.2-1.5.8</version>
        </dependency>
    </dependencies>

Stacktrace: 

> Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_dnn in java.library.path
Disconnected from the target VM, address: '127.0.0.1:56745', transport: 'socket'
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1825)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1416)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
	at org.bytedeco.opencv.global.opencv_dnn.<clinit>(opencv_dnn.java:20)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1282)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
	at org.bytedeco.opencv.opencv_objdetect.CascadeClassifier.<clinit>(CascadeClassifier.java:41)
	at Main.main(Main.java:31)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Heiko\.javacpp\cache\opencv-4.6.0-1.5.8-windows-x86_64-gpu.jar\org\bytedeco\opencv\windows-x86_64-gpu\jniopencv_dnn.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1772)
	... 11 more

Code:
 
>  FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("C://tmp//test.mp4");
  CascadeClassifier classifier = new CascadeClassifier("E:/opencv/sources/data/haarcascades/haarcascade_frontalface_alt.xml");

xml-File ist original from OpenCV 4.6. Distribution.

Code crashs on "CascadeClassifier classifier = new CascadeClassifier ...."

Dep-Check: 

    try {
            Loader.load(CascadeClassifier.class);
        } catch (UnsatisfiedLinkError e) {
            new ProcessBuilder("c:/tmp/DependenciesGui.exe", "C:/Users/Heiko/.javacpp/cache/opencv-4.6.0-1.5.8-windows-x86_64-gpu.jar/org/bytedeco/opencv/windows-x86_64-gpu/jniopencv_dnn.dll").start().waitFor();
        }

Output: 
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/4211748/215296058-541b4525-77bc-433e-808a-a8a5db074a42.png">

looks all deps are correct. 

what's wrong ? 

mfg
heiko

**Comment by saudet** [comment]
Please try again with the snapshots: http://bytedeco.org/builds/

**Comment by targit007** [comment]
Thanks for your reply. 

Test with: 

>  <dependencies>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.9-SNAPSHOT</version>
        </dependency>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform-gpu</artifactId>
            <version>4.6.0-1.5.8</version>
        </dependency>

        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>5.1.2-1.5.8</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>

Same Exception: 

> java.lang.UnsatisfiedLinkError: no jniopencv_dnn in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.opencv.global.opencv_dnn.<clinit>(opencv_dnn.java:20)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1226)
	at Main.main(Main.java:24)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Heiko\.javacpp\cache\opencv-4.7.0-1.5.9-20230127.054149-61-windows-x86_64.jar\org\bytedeco\opencv\windows-x86_64\jniopencv_dnn.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
	... 10 more


deps check:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/4211748/215297633-342d958d-f5f7-499b-8773-64e6f43d8caf.png">

wonder where are the missing dlls ?  I expect that bootstrap process copy theses files to cache folder ?

**Comment by targit007** [comment]
Ahhhh. Works with adjusted pom:

 <dependencies>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.9-SNAPSHOT</version>
        </dependency>
        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform-gpu</artifactId>
            <version>4.7.0-1.5.9-SNAPSHOT</version>
        </dependency>

        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform-gpl</artifactId>
            <version>5.1.2-1.5.9-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>

**Comment by saudet** [comment]
I guess whatever the issue was, it got fixed with OpenCV 4.7.0.

**Comment by targit007** [comment]
ok. thanks for your help and fast reply !!!

**Comment by saudet** [comment]
Version 1.5.9 has been released with OpenCV 4.7.0. Enjoy!
