### ISSUE TITLE
macosx-arm64 library build for onnx error 

### ISSUE THREAD

**Issue by OuYubin** [bytedeco/javacpp-presets#1339]
I tried to complete onnx M1 Silicon Support manually, packaged and compiled without problems, and generated the jar files without problems, but when I used it, Throw an exception.
```
macosx-arm64/libjnionnx.dylib, 0x0001): symbol not found in flat namespace '_onnxGetBackendCompatibility'
```

the following exception occurred and I was hoping for help. thanks
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnionnx in java.library.path: /Users/ouyubin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2423)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:808)
	at java.base/java.lang.System.loadLibrary(System.java:1893)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1825)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1416)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
	at org.bytedeco.onnx.global.onnx.<clinit>(onnx.java:14)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1282)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
	at org.bytedeco.onnx.ISchemaRegistry.<clinit>(ISchemaRegistry.java:16)
	at onnx.LoadModel.main(LoadModel.java:9)
Caused by: java.lang.UnsatisfiedLinkError: /Users/ouyubin/.javacpp/cache/onnx-1.12.0-1.5.8-macosx-arm64.jar/org/bytedeco/onnx/macosx-arm64/libjnionnx.dylib: dlopen(/Users/ouyubin/.javacpp/cache/onnx-1.12.0-1.5.8-macosx-arm64.jar/org/bytedeco/onnx/macosx-arm64/libjnionnx.dylib, 0x0001): symbol not found in flat namespace '_onnxGetBackendCompatibility'
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1772)
```

**Comment by saudet** [comment]
We can most likely fix that with a `new Info("onnxGetBackendCompatibility").skip()`:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#skipping-lines-from-header-files

**Comment by saudet** [comment]
I've added macosx-arm64 to the builds for ONNX.
Please give it a try with the snapshots: http://bytedeco.org/builds/
