### ISSUE TITLE
[cuda] NVML causes UnsatisfiedLinkError

### ISSUE THREAD

**Issue by masterav10** [bytedeco/javacpp-presets#1350]
I get the following error when I try to use NVML. This is on a Windows 10 box.

```
Caused by: java.lang.UnsatisfiedLinkError: %USERPROFILE%\.javacpp\cache\cuda-11.8-8.6-1.5.8-windows-x86_64.jar\org\bytedeco\cuda\windows-x86_64\jninvml.dll: The specified procedure could not be found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1772)
```

I installed the following:
1) cuda_11.8.0_522.06_windows.exe
2) cudnn-windows-x86_64-8.6.0.163_cuda11-archive.zip

I tried updating all the visual studio runtimes, that didn't make a difference.

Am I missing another dependency somewhere? The build file seems to install zlib, but I think that is for tensor stuff?

The rest of the CUDA stuff seems to work fine.

I haven't tried the snapshot yet, will do later.

**Comment by saudet** [comment]
It just sounds like the version of your video driver is too old. Please install the latest version.

**Comment by masterav10** [comment]
![image](https://user-images.githubusercontent.com/3239352/235851623-bc278678-775a-4046-93ae-68a98d2ef7a3.png)

Just installed the latest driver. Still fails.

**Comment by saudet** [comment]
Well, it works fine for me. Please try with the snapshots for CUDA 12.1: http://bytedeco.org/builds/

**Comment by masterav10** [comment]
Well that worked, but I fear there is something wrong with the 1.5.8 released version.

I have a path forward though.

We should probably leave this open until 1.5.9 is released.

**Comment by saudet** [comment]
Version 1.5.9 has been released! Let me know if you're having any problems with that one.

**Comment by masterav10** [comment]
Thank you sir, it appears to be working with the new release.
