### ISSUE TITLE
UnsatisfiedLinkError jniOpenCL on Mac M2 with onnxruntime-platform

### ISSUE THREAD

**Issue by alawasoft** [bytedeco/javacpp-presets#1389]
**Issue**
When trying to use the onnxruntime-platform on a Mac with an M1 chip, I'm encountering an UnsatisfiedLinkError related to jniOpenCL.

```
java.lang.UnsatisfiedLinkError: no jniOpenCL in java.library.path: /Users/campin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2015)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.opencl.global.OpenCL.<clinit>(OpenCL.java:14)
```

using this import 
`  .settings(libraryDependencies += "org.bytedeco" % "onnxruntime-platform" % "1.15.0-1.5.9")`
  
  
To Reproduce

1. Import onnxruntime-platform version 1.15.0-1.5.9 in a project.
2. Try to get an instance of OrtEnvironment with OrtEnvironment.getEnvironment().
3. See error

`  val env: OrtEnvironment = OrtEnvironment.getEnvironment()`

**Environment** 
OS: macOS
Chip: M2
Java version: [e.g., 18.0.2]
Scala version: [e.g., 2.13.6]
ONNX Runtime version: 1.15.0-1.5.9

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by saudet** [comment]
Are you trying to run this in native mode with an ARM version of the JDK? If so, binaries for that are not available, so that's normal.

**Comment by alawasoft** [comment]
> I've added macosx-arm64 to the builds for ONNX Runtime. Please give it a try with the snapshots: http://bytedeco.org/builds/

sorry for taking this long to reply, i just got a hold of my mac, was using windows machine for a while now.

after testing with mac m2, i got this error

```
Caused by: java.lang.UnsatisfiedLinkError: /**/libs/opencl-3.0-1.5.11-macosx-x86_64.jar/org/bytedeco/opencl/macosx-x86_64/libjniOpenCL.dylib: dlopen(/**/libs/opencl-3.0-1.5.11-macosx-x86_64.jar/org/bytedeco/opencl/macosx-x86_64/libjniOpenCL.dylib, 0x0001): symbol not found in flat namespace '_clCloneKernel'
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2402)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2028)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
	... 41 more
```

**Comment by alawasoft** [comment]
Sorry for taking a while to reply your message, I just got a hold of my mac m2, been using windows machine for a while.

I've tested the SNAPSHOT version, and it worked.

but for some reason, org.bytedeco.javacpp.Loader.Detector.getPlatform detected my machine as macosx-x86_64 instead of macosx-arm64.

thanks!
