### ISSUE TITLE
Urgent: couldn't find "libjniavutil.so"

### ISSUE THREAD

**Issue by arthurpalves** [bytedeco/javacpp-presets#151]
I'm trying to use `FfmpegFrameRecorder`, however, trying the following gives me an `UnsatisfiedLinkError: org.bytedeco.javacpp.avutil`:

```
        converter = new OpenCVFrameConverter.ToIplImage();
        recorder = new FFmpegFrameRecorder(mDstPath, mWidth, mHeight);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFormat("hls");
        recorder.setFrameRate(30);
        recorder.setVideoCodec(13);
        recorder.setPixelFormat(0);
        recorder.setVideoBitrate(10 * 1024 * 1024);
```

My `build.gradle` has:
```
    compile 'org.bytedeco:javacv:1.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-x86'
```

The same continues to happen even using `.jar`s and/or extracting the `.so` directly to my `armeabi-v7a` folder.

**OBS**
I finally added the following line before any call to `FFmpegFrameRecorder`:
`Loader.load(avutil.class);`

That gives me:
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qviky.qviky.debuggable-2/base.apk"],nativeLibraryDirectories=[/data/app/com.qviky.qviky.debuggable-2/lib/arm, /data/app/com.qviky.qviky.debuggable-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libjniavutil.so"
 at java.lang.Runtime.loadLibrary(Runtime.java:367)
 at java.lang.System.loadLibrary(System.java:1076)
 at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
 at org.bytedeco.javacpp.Loader.load(Loader.java:438)
 at org.bytedeco.javacpp.Loader.load(Loader.java:381)
 at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:324)
 at org.bytedeco.javacpp.Loader.load(Loader.java:413)
```

I've checked the apk and it contains the following libs under `/lib/armeabi-v7a`:
```
   8618672 Feb 15 17:34 libavcodec.so
     50904 Feb 15 17:34 libavdevice.so
    813784 Feb 15 17:34 libavfilter.so
   1440292 Feb 15 17:34 libavformat.so
    279932 Feb 15 17:34 libavutil.so
  11661268 Feb 15 17:34 libffmpeg.so
    873784 Feb 15 17:34 libopencv_calib3d.so
   1082760 Feb 15 17:34 libopencv_contrib.so
   2448284 Feb 15 17:34 libopencv_core.so
    922936 Feb 15 17:34 libopencv_features2d.so
    697660 Feb 15 17:34 libopencv_flann.so
    574776 Feb 15 17:34 libopencv_gpu.so
   2425640 Feb 15 17:34 libopencv_highgui.so
   2164156 Feb 15 17:34 libopencv_imgproc.so
     13332 Feb 15 17:34 libopencv_info.so
   1252160 Feb 15 17:34 libopencv_legacy.so
    822736 Feb 15 17:34 libopencv_ml.so
    423224 Feb 15 17:34 libopencv_nonfree.so
    439940 Feb 15 17:34 libopencv_objdetect.so
    128128 Feb 15 17:34 libopencv_photo.so
    656700 Feb 15 17:34 libopencv_stitching.so
    304312 Feb 15 17:34 libopencv_video.so
    521528 Feb 15 17:34 libopencv_videostab.so
     66804 Feb 15 17:34 libpostproc.so
     79092 Feb 15 17:34 libswresample.so
    275700 Feb 15 17:34 libswscale.so
    230616 Feb 15 17:34 libtbb.so
```

Proguard is disabled.

What could be the cause and solution?

**Comment by saudet** [comment]
You're missing the set of libjni*.so files.

**Comment by arthurpalves** [comment]
Can't find them anywhere @saudet.  
If I try to build myself I get to the last command:
`mvn clean install -Djavacpp.platform=android-xxx -Djavacpp.platform.root=/path/to/android-ndk/ -Djavacpp.platform.compiler=/path/to/target-g++`

But always get this error:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaCPP Presets .................................... SUCCESS [  2.195 s]
[INFO] JavaCPP Presets for OpenCV ......................... FAILURE [  0.067 s]
[INFO] JavaCPP Presets for FFmpeg ......................... SKIPPED
[INFO] JavaCPP Presets for FlyCapture ..................... SKIPPED
[INFO] JavaCPP Presets for libdc1394 ...................... SKIPPED
[INFO] JavaCPP Presets for libfreenect .................... SKIPPED
[INFO] JavaCPP Presets for videoInput ..................... SKIPPED
[INFO] JavaCPP Presets for ARToolKitPlus .................. SKIPPED
[INFO] JavaCPP Presets for Chilitags ...................... SKIPPED
[INFO] JavaCPP Presets for flandmark ...................... SKIPPED
[INFO] JavaCPP Presets for FFTW ........................... SKIPPED
[INFO] JavaCPP Presets for GSL ............................ SKIPPED
[INFO] JavaCPP Presets for LLVM ........................... SKIPPED
[INFO] JavaCPP Presets for Leptonica ...................... SKIPPED
[INFO] JavaCPP Presets for Tesseract ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.474 s
[INFO] Finished at: 2016-02-16T17:25:59+02:00
[INFO] Final Memory: 18M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.bytedeco:javacpp:1.2-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.bytedeco:javacpp:jar:1.2-SNAPSHOT -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.bytedeco:javacpp:1.2-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.bytedeco:javacpp:jar:1.2-SNAPSHOT
```

**Comment by saudet** [comment]
Please run mvn install on the javacpp module first!

**Comment by arthurpalves** [comment]
I already did that, tried several times. I'm doing all the steps with success until the last one.
Also, I noticed the following before the error per se:

```
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:opencv:jar:3.1.0-1.2-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:opencv:3.1.0-${project.parent.version}, /Users/arthuralves/Projects/javacpp-presets/opencv/pom.xml, line 14, column 12
```

Anything related to that?

**Comment by saudet** [comment]
That's just a warning. It doesn't have anything to do with the error. The error means you simply forgot to install the `javacpp` module first.

**Comment by arthurpalves** [comment]
Actually, that was my mistake, too many Terminal tabs, got into the wrong one, running as a different user, which of course would cause the error. I've ran into another issue running that, not related to this thread, so I'll open another and close this one. Thanks @saudet!

**Comment by VladimirLichonos** [comment]
How do you get libjniavutil.so and etc.? I could compile all presets, but I can't get javacpp.jar to produce .so files, any reference. I tried to run based on readme, but not sure what's bin and bin/classes folders?

**Comment by saudet** [comment]
@VladimirLichonos All the info is here: https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by VladimirLichonos** [comment]
@saudet thank you for quick response, I've produced basically same list as above of so files, but no libjniavutil.so. Can't figure out how to get it though. I think I went through documentation, I am trying to compile for Android.

**Comment by saudet** [comment]
There's a recent build here, so you could just use that:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/

**Comment by VladimirLichonos** [comment]
Tried to use it,

```groovy
compile ('org.bytedeco:javacv:1.2-SNAPSHOT') {
    exclude module: 'flycapture'
    exclude module: 'libdc1394'
    exclude module: 'artoolkitplus'
    exclude module: 'caffe'
    exclude module: 'chilitags'
    exclude module: 'cuda'
    exclude module: 'fftw'
    exclude module: 'flandmark'
    exclude module: 'gsl'
    exclude module: 'leptonica'
    exclude module: 'libfreenect'
    exclude module: 'llvm'
    exclude module: 'mxnet'
    exclude module: 'tensorflow'
    exclude module: 'tesseract'
    exclude module: 'videoinput'
}
compile 'org.bytedeco:javacpp:1.2-SNAPSHOT'
compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.2-SNAPSHOT:android-x86' // android-arm
compile 'org.bytedeco.javacpp-presets:ffmpeg:3.0-1.2-SNAPSHOT:android-x86' // android-arm
```

But still it tries to look for all these dependencies snapshot version, which none of them exist. In then giving me this:

```
Error:Could not find javacpp-presets-Mac OS X-x86_64.jar (org.bytedeco:javacpp-presets:1.2-SNAPSHOT).
Searched in the following locations:
    http://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/1.2-SNAPSHOT/javacpp-presets-1.2-20160319.155454-5-Mac OS X-x86_64.jar
```

Thank you for your help, I am also still trying to compile everything. I could not use 1.1 version, becuase getting error so contains text reallocation (or something) on Marshmallow 6.0 Android.

**Comment by saudet** [comment]
@VladimirLichonos Try to copy the JAR files themselves manually into your project.

**Comment by VladimirLichonos** [comment]
Perfect, thank you! I ended up moving jars into libs folder manually, since gradle right now trying to do weird things.
