### ISSUE TITLE
sun.reflect.annotation.TypeNotPresentExceptionProxy

### ISSUE THREAD

**Issue by bwkchee** [bytedeco/javacpp-presets#184]
I'm trying to use the pre-built jars and have gotten them to successfully work with code on one Ubuntu 15 based system which already has caffe installed but not currently on my path or LD_LIBRARY_PATH.  I'm trying to get the same code working on a centos 7 and another Ubuntu 15 based system but I keep on getting the following error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at edu.jhuapl.caffe.TestCPU.main(TestCPU.java:7)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:133)
	at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:211)
	at org.bytedeco.javacpp.Loader.load(Loader.java:399)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.caffe$Caffe.<clinit>(caffe.java:584)
```
I've tried with both Oracle Java 8 and OpenJDK 7 the minimal test case I've come up is below.  If I don't do Caffe.set_mode the error is similar for whatever the next Caffe call I make (ie. intializing a float network: caffe_net = new FloatNet(model, TEST);).  

TestCPU class:
```java
import org.bytedeco.javacpp.caffe.Caffe;
public class TestCPU {
	public static void main(String[] args){
		Caffe.set_mode(Caffe.CPU);
	}
}
```
I'm executing as:
```
java -cp "caffe.jar:caffe-linux-x86_64.jar:javacpp.jar:slimjar_test.jar" edu.jhuapl.caffe.TestCPU
```

**Comment by saudet** [comment]
You've got a mismatching version of JavaCPP somewhere on those systems.

**Comment by bwkchee** [comment]
All of the jars are from the binary download of javacpp-presets.

**Comment by bwkchee** [comment]
The specification versions match in the manifest for caffe.jar and javacpp.jar

The manifest for caffe is:
Manifest-Version: 1.0
Implementation-Vendor: Bytedeco
Implementation-Title: JavaCPP Presets for Caffe
Implementation-Version: master-1.1
Built-By: root
Build-Jdk: 1.7.0_85
Class-Path: ./ javacpp.jar caffe-linux-arm.jar caffe-linux-x86.jar caffe-linux-x86_64.jar caffe-macosx-x86.jar caffe-macosx-x86_64.jar caffe-windows-x86.jar caffe-windows-x86_64.jar opencv-3.0.0-1.1.jar javacpp-1.1.jar
Specification-Vendor: Bytedeco
Name: org/bytedeco/javacpp/presets/
Specification-Title: JavaCPP Presets for Caffe
Created-By: Apache Maven 3.0.5
Specification-Version: master-1.1
Archiver-Version: Plexus Archiver

Java CPP:
Manifest-Version: 1.0
Implementation-Title: JavaCPP
Implementation-Version: 1.1
Archiver-Version: Plexus Archiver
Built-By: saudet
Specification-Vendor: Bytedeco
Specification-Title: JavaCPP
Class-Path: ./
Main-Class: org.bytedeco.javacpp.tools.Builder
Implementation-Vendor: Bytedeco
Name: org/bytedeco/javacpp/
Created-By: Apache Maven 3.2.2
Build-Jdk: 1.8.0_60
Specification-Version: 1.1

**Comment by saudet** [comment]
There are conflicting JAR files somewhere on your class path. Please look for them.

**Comment by bwkchee** [comment]
I'm trying to use the pom now and am getting the following error on the centos 7 system:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
	at org.bytedeco.javacpp.Loader.load(Loader.java:438)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.caffe.<clinit>(caffe.java:16)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:413)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.caffe$Caffe.<clinit>(caffe.java:584)
	at edu.jhuapl.caffe.TestCPU.main(TestCPU.java:7)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp3067252925365737/libjnicaffe.so: libcudart.so.7.5: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:580)
	... 9 more

pom.xml:
<dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>javacpp</artifactId>
	<version>1.1</version>
</dependency>  
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>caffe</artifactId>
    <version>master-1.1</version>
    </dependency>
<dependency>
	<groupId>org.bytedeco.javacpp-presets</groupId>
	<artifactId>cuda</artifactId>
	<version>7.5-1.1</version>
</dependency>
    <dependency>
	<groupId>org.bytedeco.javacpp-presets</groupId>
	<artifactId>opencv</artifactId>
	<version>3.0.0-1.1</version>
</dependency>

**Comment by saudet** [comment]
Please include the `lib` directory of CUDA in your `/etc/ld.so.conf` file or something, as per the installation instructions of CUDA.
