### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_stitching in java.library.path

### ISSUE THREAD

**Issue by NickPakhomov** [bytedeco/javacpp-presets#198]
Using latest JavaCPP OpenCV presets library, OpenCV 3.1.0 downloaded from the website and compiled with CMake for Mac OS X 10.11.4.

Here's the error list that I get:

```
objc[41249]: Class CaptureDelegate is implemented in both lib/libopencv_java310.dylib and /private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/libopencv_videoio.3.0.dylib. One of the two will be used. Which one is undefined.
objc[41249]: Class CVWindow is implemented in both /lib/libopencv_java310.dylib and /private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/libopencv_highgui.3.0.dylib. One of the two will be used. Which one is undefined.
objc[41249]: Class CVView is implemented in both lib/libopencv_java310.dylib and /private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/libopencv_highgui.3.0.dylib. One of the two will be used. Which one is undefined.

objc[41249]: Class CVSlider is implemented in both lib/libopencv_java310.dylib and /private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/libopencv_highgui.3.0.dylib. One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_stitching in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
	at org.bytedeco.javacpp.Loader.load(Loader.java:438)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.opencv_stitching.<clinit>(opencv_stitching.java:22)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:413)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.opencv_stitching$Stitcher.<clinit>(opencv_stitching.java:2705)
	at ru.nov.elsy.agroscan.Stitching.main(Stitching.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/libjniopencv_stitching.dylib: dlopen(/private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/libjniopencv_stitching.dylib, 1): Library not loaded: @rpath/libopencv_xfeatures2d.3.0.dylib
  Referenced from: /private/var/folders/y3/yvx6lrj55pdgh1q933xx1j700000gn/T/javacpp477114127222120/./libopencv_stitching.3.0.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:580)
	... 14 more

Process finished with exit code 1
```

The issue came up after I've updated JavaCPP library from 2.x to 3.x due to the patented SURF algorithm I need for my image stitching software.

**Comment by saudet** [comment]
That's been fixed, see https://github.com/bytedeco/javacpp/issues/38 and #181. Please try with the latest code from the master branches.
