### ISSUE TITLE
javacv1.1--opencv3.0.0 compile

### ISSUE THREAD

**Issue by linghushaoxia** [bytedeco/javacpp-presets#206]
hi ,all, there is a strange trouble.
I try to compile the opencv in my computer and all the libs are compiled
the steps as follows:
1. cd to the /javacpp-presets/opencv
./cppbuild.sh -platform macosx-x86_64 install
2. mvn install
after the above, the libs is compiled to the /javacpp-presets/opencv/cppbuild/macosx-x86_64/lib
i download other jar from maven center,then i copy  four jars to the project's lib folder ,add them to the java build path.
The four jars is javacv.jar, javacpp.jar, opencv.jar and opencv-macosx-x86_64.jar,of course the version is 1.1 then i detete the /javacpp-presets/opencv/cppbuild/macosx-x86_64/lib.
The trouble is coming! I run the java app to read and show or save the image  is ok,but when i test the  SIFT class ,it has a wrong
`org.bytedeco.javacpp.opencv_xfeatures2d.SIFT.create(int nfeatures, int nOctaveLayers, double contrastThreshold, double edgeThreshold, double sigma)`
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_xfeatures2d in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
	at org.bytedeco.javacpp.Loader.load(Loader.java:438)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.opencv_xfeatures2d.<clinit>(opencv_xfeatures2d.java:19)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.bytedeco.javacpp.Loader.load(Loader.java:413)
	at org.bytedeco.javacpp.Loader.load(Loader.java:381)
	at org.bytedeco.javacpp.opencv_xfeatures2d$SIFT.<clinit>(opencv_xfeatures2d.java:423)
	at opencv2_cookbook.chapter08.Ex6SIFT.main(Ex6SIFT.java:38)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/55/njj3mfvj1ql1nl8d_85tx8740000gn/T/javacpp1460820213873177000/libjniopencv_xfeatures2d.dylib: dlopen(/private/var/folders/55/njj3mfvj1ql1nl8d_85tx8740000gn/T/javacpp1460820213873177000/libjniopencv_xfeatures2d.dylib, 1): Library not loaded: @rpath/libopencv_shape.3.0.dylib
  Referenced from: /private/var/folders/55/njj3mfvj1ql1nl8d_85tx8740000gn/T/javacpp1460820213873177000/./libopencv_xfeatures2d.3.0.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:580)
	... 9 more`
I restore the deleted /javacpp-presets/opencv/cppbuild/macosx-x86_64/lib from trash the test is ok.
I guess the cppbuild.sh write the /javacpp-presets/opencv/cppbuild/macosx-x86_64/lib to the system env. But i print the env and properties use
 `System.out.println(System.getenv());
System.out.println(System.getProperties());`
the result does not contain the /javacpp-presets/opencv/cppbuild/macosx-x86_64/lib
and i open the bash terminal ，the env  does not contain the /javacpp-presets/opencv/cppbuild/macosx-x86_64/lib ethier.
I don't know the reason,please guide me.
Thanks a lot!

**Comment by saudet** [comment]
Does the same thing happen with the latest 1.2-SNAPSHOT?

**Comment by saudet** [comment]
Please try again with version 1.2, thank you!

**Comment by linghushaoxia** [comment]
ok,if I need ,i will;thanks!
