### ISSUE TITLE
MS Windows recognizes jniavutil as virus and removes it. Version 3.0.2-1.2

### ISSUE THREAD

**Issue by mtadmk** [bytedeco/javacpp-presets#221]
After updating ffmpeg to new version Windows defender automaticaly recognizes jniavutil as virus and removes it:
```
Exception in thread "Thread-4" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2719)
	at Tutorial01.realStart(Tutorial01.java:94)
	at Tutorial01.lambda$startCamera$1(Tutorial01.java:223)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\User\AppData\Local\Temp\javacpp251083592844989\jniavutil.dll: Operacja nie zakończyła się pomyślnie, ponieważ plik zawiera wirusa lub potencjalnie niechciane oprogramowanie
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
	... 11 more
```

**Comment by saudet** [comment]
Try to set a cache dir instead:
https://github.com/bytedeco/javacpp/issues/60#issuecomment-191773634

**Comment by mtadmk** [comment]
@saudet There is no change. I can put cache directory to white list and make it work. The problem will still exists on other machines yet.

**Comment by saudet** [comment]
Well, Windows Defender doesn't complain on my machine, so it might something only with your machine... Could you try it on other machines?

**Comment by mtadmk** [comment]
I checked on other machine but apparently all of us have the same environment and the problem is repeatable. Windows 10 x64 with Defender.

**Comment by saudet** [comment]
It works just fine here, so I will not be able to debug something that is isn't broken. If you could try to build from source and figure out what makes it fail on your machines, it would help a lot!

**Comment by mtadmk** [comment]
Well I would rather use the old version until clarification. Defender found Trojan:Win32/Repjexi in jniavutil.dll (the cause of dll removal). Although MS Defender may not be the very best software, it looks like a serious security issue to me.

**Comment by saudet** [comment]
No it's not serious. It's quite common with FFmpeg, for example:
http://forum.videohelp.com/threads/369276-FFmpeg-2-5-portable-Infected-with-Virus-or-Something

**Comment by mtadmk** [comment]
True. Just found also https://github.com/iBotPeaches/Apktool/issues/1054 . So now shall we wait for Defender update?

**Comment by saudet** [comment]
Report it to Microsoft?

**Comment by mtadmk** [comment]
Already reported in [here](http://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps/defender-treats-jniavutildll-as-trojanwin32repjexi/17df88ec-31b7-47d1-af9d-8a2a8ea2b290?auth=1)

**Comment by mtadmk** [comment]
I think this is no longer valid. I extracted manually jniavutil from (downloaded by maven) jar and updated Defender no longer threats is as trojan.

**Comment by saudet** [comment]
Good to hear it's no longer an issue. Thanks for reporting!

**Comment by SpaceboyRoss01** [comment]
I'm developing stuff on java and I use jni. Windows 10 defender also tells me that its a virus.
Git: https://github.com/SpaceboyRoss01/jnix

**Comment by saudet** [comment]
Please report it to Microsoft, not here, thank you.
