### ISSUE TITLE
ClassNotFoundException: org.bytedeco.javacpp.avutil$Pool_free_Pointer on 3.0.2-1.2 version

### ISSUE THREAD

**Issue by mtadmk** [bytedeco/javacpp-presets#225]
When trying to run code from tutorial on line
`final AVFormatContext pFormatCtx = new AVFormatContext(null);`
class not found exception is being thrown:
```
 Exception in thread "Thread-5" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2719)
	at Tutorial01.realStart(Tutorial01.java:126)
	at Tutorial01.lambda$startCamera$1(Tutorial01.java:321)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$Pool_free_Pointer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.putMemberOffset(Loader.java:749)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	... 8 more

Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer. 
```

It is the same when using cachedir or not. With cacheDir there are only 2 dll in directory:
avutil-55.dll
jniavutil.dll

maven dependency:
```
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>3.0.2-1.2</version>
        </dependency>
```

or with 64bit:
```        
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>3.0.2-1.2</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>3.0.2-1.2</version>
            <classifier>windows-x86_64</classifier>
        </dependency>
```

**Comment by saudet** [comment]
It works just fine here. I won't be able to fix a problem that I cannot reproduce, so you're going to need to provide more details about your environment.

**Comment by mtadmk** [comment]
Environment: 
WIndows 10 x64
Java jdk 1.8.0_91-b14 x64
Intellij 2016.1 with maven

Version 2.8.1-1.1 works perfectly fine.

**Comment by Manevolent** [comment]
Same issue, IntelliJ 14.1.3 on Windows 10 x64, JRE 1.8.0_91-b14 x64

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avformat.<clinit>(avformat.java:14)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$Pool_free_Pointer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at org.bytedeco.javacpp.Loader.putMemberOffset(Loader.java:749)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	... 6 more
Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer.
```

**Comment by saudet** [comment]
It just looks like you guys have an old version of JavaCPP in the class
path somewhere...

**Comment by flonix8** [comment]
Same here on Windows 10 x64 (using Java 1.8.0_92-b14, 64-bit).

In my case there can't be any old versions of javaCPP hanging around as I'm on a freshly installed machine and have just started working with javaCPP.

I even tried to set classpath explicitly on the command line:
```
C:\Users\xyz\workspace3\tutorial01\target>java -cp tutorial01-1.2.jar;C:\Users\xyz\.m2\repository\org\bytedeco\javacpp\1.2\javacpp-1.2.jar;C:\Users\xyz\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.0.2-1.2\ffmpeg-3.0.2-1.2-windows-x86_64.jar;C:\Users\xyz\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.0.2-1.2\ffmpeg-3.0.2-1.2.jar de.xyz.ffmpeg_test.Tutorial01
Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:464)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2719)
        at de.xyz.ffmpeg_test.Tutorial01.main(Tutorial01.java:52)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$Pool_free_Pointer
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.putMemberOffset(Loader.java:749)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
        at org.bytedeco.javacpp.Loader.load(Loader.java:492)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
        ... 6 more
```

**Comment by saudet** [comment]
Could you guys try again with JavaCPP 1.2.1? I've fixed a couple of things that are probably not related, but we never know. It's compatible with the presets built with JavaCPP 1.2 anyway.

**Comment by enternoescape** [comment]
I too am having this issue on Windows 8.1 x64 and x86 with 1.2. I tried 1.2.1. There was no improvement. Also, from what I could tell while debugging, it does actually find the right .jar file that contains the native .dll files.

**Comment by saudet** [comment]
I see what the issue is. The Zeranoe binaries don't have a build for 3.0.2 and the closest build included a new class that wasn't in 3.0.2. Building from source will fix this issue, but JavaCPP should be made not to crash on something like that...

**Comment by saudet** [comment]
Or maybe not, it shouldn't just ignore errors about missing classes. Anyway, here a JAR file containing the missing classes: [ffmpeg-3.0.2-1.2-fixed.zip](https://github.com/bytedeco/javacpp-presets/files/290338/ffmpeg-3.0.2-1.2-fixed.zip)

**Comment by enternoescape** [comment]
I will test this, but does this extra type mean I'll need to use different ffmpeg-3.0.2-1.2.jar files between my Linux and Windows builds? Or will the Linux build not care that there an "extra" unused type?

**Comment by enternoescape** [comment]
![repjexi](https://cloud.githubusercontent.com/assets/4162345/15683374/ff24acd2-272f-11e6-80bb-a259d34e309d.PNG)
Now everything loaded, but Windows Defender detected a virus in one of the jni files. I don't know if this is a common issue with FFmpeg, but I just wanted to bring it up.

**Comment by saudet** [comment]
The Linux binaries shouldn't care about the extra classes, no.

**Comment by enternoescape** [comment]
It would appear that the Linux binaries have classes not present in the Windows binaries, so as it turns out, the jar file you posted will only work for Windows. It also contains the deprecation of AVStream.codec. The Linux version doesn't even know what AVCodecParameter is. I switched to the jar provided by Maven and this following exception went away for Linux. I hope we can find a way to get these synced back up.

java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil.AV_PIX_FMT_GBRAP12()I
	at org.bytedeco.javacpp.avutil.AV_PIX_FMT_GBRAP12(Native Method)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:2729)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.bytedeco.javacpp.Loader.load(Loader.java:472)
	at org.bytedeco.javacpp.Loader.load(Loader.java:417)
	at org.bytedeco.javacpp.avutil$Callback_Pointer_int_String_Pointer.<clinit>(avutil.java:1658)

**Comment by saudet** [comment]
I see, we can't use builds from Zeranoe then... Here are some binaries built from source that work properly: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0.2-1.2.1-SNAPSHOT/

**Comment by enternoescape** [comment]
I get a different kind of error with that build. I checked the path mentioned in the stack trace and I see jniavutil.dll and avutil-55.dll are in the same folder which I presume are the correct libraries. This happens with 32-bit and 64-bit. I don't know how relevant it is, but the property java.library.path does not include the temp folder.

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:702)
	at org.bytedeco.javacpp.Loader.load(Loader.java:500)
	at org.bytedeco.javacpp.Loader.load(Loader.java:417)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:472)
	at org.bytedeco.javacpp.Loader.load(Loader.java:417)
	at org.bytedeco.javacpp.avutil$Callback_Pointer_int_String_Pointer.<clinit>(avutil.java:1658)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\...\AppData\Local\Temp\javacpp937617066645800\jniavutil.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:685)
	... 11 more

**Comment by saudet** [comment]
@enternoescape I've fixed the builds to prevent the DLLs from missing dependencies: https://github.com/bytedeco/javacpp-presets/commit/a1723f48c68e858fd464df9f3ed851d224d6ebb7

I've also deployed new SNAPSHOT binaries at the same place as before:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0.2-1.2.1-SNAPSHOT/

**Comment by brandon8863** [comment]
The 1.2.1-SNAPSHOT fixed the Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer. issue for me

**Comment by enternoescape** [comment]
@saudet Thanks. That snapshot looks good on Windows. I haven't had any surprises so far.

**Comment by rickfluck** [comment]
@saudet New SNAPSHOT worked for me on Windows 10 for opening .mp4 files using FFmpegFrameGrabber.createDefault(String). Thank you for all that you do for the great library. -Rick

**Comment by Shatterhand** [comment]
Hey! I am getting this exception with the base 1.2 binaries when trying to grab a frame from a video:
`java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil`

If I use this fixed ffmpeg.jar (https://github.com/bytedeco/javacpp-presets/files/290338/ffmpeg-3.0.2-1.2-fixed.zip) I can grab frames from the video but it will throw this exception when trying to record a frame in a video:
`org.bytedeco.javacv.FrameRecorder$Exception: avcodec_find_encoder() error: Video codec not found`

I tried all the jars from this link too (https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0.2-1.2.1-SNAPSHOT/) none of them worked.

**Comment by saudet** [comment]
@Shatterhand Check the messages on the console. It'll tell you what codec it's looking for and you can then add it.

**Comment by Shatterhand** [comment]
@saudet It didnt say anything about the codec, but I was reading a tscc video and was recording with the same codec:
`recorder.setCodec(grabber.getCodec());`

**Comment by catherineHR** [comment]
Hello, I'm using May16' (JavaCV 1.2) versions of javaCV and javaCPP, using Android Studio.
When creating a FrameGrabber : 
`FrameGrabber grabber = new FFmpegFrameGrabber(myvid);` (it's a MP4 file), I'm getting the following error:
Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/bytedeco/javacpp/avutil;

Any idea to resolve this? Thanks!

**Comment by catherineHR** [comment]
Actually I've put the uncompressed *.so files of ffmpeg-android-arm and opencv-android-arm in jniLibs/armeabi, and I erased them from the gradle file. Now I don't have the UnsatisfiedLinkError anymore, I pass the FrameGrabber creation, but the grabber.start() failed afterwards.

**Comment by saudet** [comment]
I've released binaries for FFmpeg 3.1.2, properly built as explained above:
https://github.com/bytedeco/javacpp-presets/tree/master/ffmpeg
Let me know if there are any issues with those. Thanks for reporting and for testing!

**Comment by eguid** [comment]
hello,I'm using May16' (JavaCV 1.2) versions of javaCV and javaCPP,using eclipse Runing report an 'ClassNotFoundException' error,Caused by:org.bytedeco.javacpp.avutil$Pool_free_Pointer
Have any idea to resolve this problem? Thanks!

**Comment by eguid** [comment]
I use this fixed ffmpeg.jar (https://github.com/bytedeco/javacpp-presets/files/290338/ffmpeg-3.0.2-1.2-fixed.zip)  report an error:java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

**Comment by saudet** [comment]
@eguid Use the latest binaries here: http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20ffmpeg

**Comment by eguid** [comment]
@saudet  It's very good, already in operation,thanks very much!

**Comment by saudet** [comment]
@paulyzheng1 You're using an old version of JavaCPP, JavaCV, or OpenCV somewhere. Make sure to use the latest versions of everything.

**Comment by paulyzheng1** [comment]
@saudet ,thanks a lot.   Today I make sure it again. When this problem happened, I almost use latest version files.
During making this app, I use these following .jars(/03/29/2018, javacv-platform-1.4.1-bin.zip)
javacv.jar
javacpp.jar
opencv.jar

And this app has a dependency library : OpenCV library 3.3.0 ;

Should I use the latest version: OpenCV library 3.4.1 ? Thanks a lot.

And I put these following .so files(/03/29/2018, javacv-platform-1.4.1-bin.zip) in /system/lib,/system/lib64:
libjniopencv_core.so
libopencv_core.so
libopencv_imgproc.so

**Comment by saudet** [comment]
@paulyzheng1 That doesn't matter, that should work. If you've enabled ProGuard, that's most likely the issue here: https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV
