### ISSUE TITLE
Couldn't load jnifftw3 /lib64/libc.so.6: version `GLIBC_2.14' not found (UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by JGuillaumin** [bytedeco/javacpp-presets#232]
Hello, 

I tried to launch the java tutorial for the preset of FFTW. 
With the same code, and configuration for Maven (Maven project in Eclipse), I have an UnsatisfiedLinkError. 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnifftw3 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:845)
	at java.lang.System.loadLibrary(System.java:1084)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:702)
	at org.bytedeco.javacpp.Loader.load(Loader.java:500)
	at org.bytedeco.javacpp.Loader.load(Loader.java:417)
	at org.bytedeco.javacpp.fftw3.<clinit>(fftw3.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.bytedeco.javacpp.Loader.load(Loader.java:472)
	at org.bytedeco.javacpp.Loader.load(Loader.java:433)
	at Example.main(Example.java:47)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp3031284702504755/libjnifftw3.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/javacpp3031284702504755/libjnifftw3.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1928)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
	at java.lang.Runtime.load0(Runtime.java:792)
	at java.lang.System.load(System.java:1059)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:685)
	... 8 more
```

My dependencies in Maven are : 
```xml
<dependency>
    	<groupId>org.bytedeco</groupId>
    	<artifactId>javacpp</artifactId>
    	<version>1.2.1</version>
</dependency>
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>fftw</artifactId>
            <version>3.3.4-1.2</version>
</dependency>
```
I have to install some parts og the native lib FFTW (in C++) or just put the dependencies in Maven ?

**Comment by saudet** [comment]
That error means your version of Linux is pretty old. If you're stuck with that, you'll need to rebuild from source: https://github.com/bytedeco/javacpp-presets/#build-instructions
