### ISSUE TITLE
Can't set up Tesseract on Android

### ISSUE THREAD

**Issue by Fandrelo** [bytedeco/javacpp-presets#275]
I tried everything so i'm doing this.

Tried adding it through gradle like it says here
https://github.com/bytedeco/javacpp-presets

https://github.com/bytedeco/javacpp-presets/issues/220
Tried every single thing in this link (including the work around) also every other link related to it (here in github/issues)

http://stackoverflow.com/questions/37981686/bytedecos-tesseract-library-was-added-through-gradle-dependency-but-not-found
Also this but it's the same thing in the first link

And i tried adding the libraries manually (*.jar)
I tried with javacpp.jar and Tesseract.jar (This is not right as far as i'm aware)
with javacpp.jar and Tesseract-android-arm.jar
and nothing i believe this is as far is i could get

`21922-21922/tesseractjar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: tesseractjar, PID: 21922
                                                                    java.lang.ExceptionInInitializerError
                                                                        at tesseractjar.MainActivity.onCreate(MainActivity.java:19)
                                                                        at android.app.Activity.performCreate(Activity.java:5231)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.lang.TypeNotPresentException: Type org/bytedeco/javacpp/presets/lept not present
                                                                        at java.lang.Class.getDeclaredAnnotation(Native Method)
                                                                        at java.lang.Class.getAnnotation(Class.java:290)
                                                                        at org.bytedeco.javacpp.ClassProperties.load(ClassProperties.java:143)
                                                                        at org.bytedeco.javacpp.Loader.loadProperties(Loader.java:235)
                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:447)
                                                                        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
                                                                        at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3648)
                                                                        at tesseractjar.MainActivity.onCreate(MainActivity.java:19) 
                                                                        at android.app.Activity.performCreate(Activity.java:5231) 
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611) 
                                                                        at dalvik.system.NativeStart.main(Native Method) `

MainActivity.java:19 is this

`TessBaseAPI tessBaseAPI = new TessBaseAPI();`
which is exactly as the example on github and the import is this
`import static org.bytedeco.javacpp.tesseract.*;`

Is it even possible to run Tesseract on android?
Maybe anybody can show me an Android Studio Project example

I did the example in [here](https://github.com/bytedeco/javacpp-presets/tree/master/tesseract) with maven in Intellij Idea and it worked however i have no luck with android

Don't even have a single idea what i am doing wrong, I'm lost, which is the reason for opening this.

Thanks in advance.

**Comment by Fandrelo** [comment]
configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
android {
    packagingOptions {
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/tesseract/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/tesseract/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/leptonica/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/leptonica/pom.xml'
    }
}

Made it work using the placing the jars int in the libs folder and adding this packagingOptions
Turns out i had to use leptonica aswell

**Comment by saudet** [comment]
Yes, glad to hear you got it working!
