### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path

### ISSUE THREAD

**Issue by nchivukula** [bytedeco/javacpp-presets#295]
I am getting following error when I used javacpp-presets for tensorflow:

[error] (run-main) java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:727)
	at org.bytedeco.javacpp.Loader.load(Loader.java:502)
	at org.bytedeco.javacpp.Loader.load(Loader.java:419)
	at org.bytedeco.javacpp.tensorflow.<clinit>(tensorflow.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:474)
	at org.bytedeco.javacpp.Loader.load(Loader.java:419)
	at org.bytedeco.javacpp.helper.tensorflow$AbstractSession.<clinit>(tensorflow.java:193)
	at TensorflowModel.init(Main.scala:15)
	at Main$.main(Main.scala:71)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

Building javacpp-presets/tensorflow (version 0.9 of tensorflow )produced libtensorflow.so. Could not find libjnitensorflow.so anywhere. I am using sbt build with IntelliJ. 

Appreciate any help on this.

Thanks in advance!!

**Comment by saudet** [comment]
Please follow the instructions for sbt here:
https://github.com/bytedeco/javacpp-presets/#downloads

**Comment by sj6077** [comment]
I'm having same issue using maven. Is there any way to solve it?

**Comment by deepakcse2k5** [comment]
i am having same issue using pyspark tensorflow on jupyter.Is there anyway to solve it?

**Comment by giorgiomondauto** [comment]
Has anyone found a solution for this? It is a quite aged issue.

**Comment by saudet** [comment]
If you're getting this on Windows, it's probably some missing DLL somewhere. We can debug this with the Dependencies tool: https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by giorgiomondauto** [comment]
@saudet Hey, I am running on a databrick cluster version: `"8.4.x-gpu-ml-scala2.12", "node_type_id": "p2.8xlarge`
with the following libraries:
`{
        "maven": {"coordinates": "ml.combust.mleap:mleap-spark-extension_2.12:0.18.1"}
    },
    {
         "maven": {"coordinates": "ml.combust.mleap:mleap-tensorflow_2.12:0.18.1"}
    },
    {
          "maven": {"coordinates": "org.mlflow:mlflow-client:1.13"}
    },
      {
          "maven": {"coordinates": "org.tensorflow:tensorflow-core-platform:0.3.1"}
    },

     {
      "maven": {"coordinates": "com.github.seratch:awscala-s3_2.12:0.8.3"}
    }

**Comment by saudet** [comment]
On Linux, it'll tell you wants missing in the error message.

**Comment by giorgiomondauto** [comment]
> On Linux, it'll tell you what's missing in the error message.

That's the msg I am getting: `UnsatisfiedLinkError: no jnitensorflow in java.library.path
Caused by: UnsatisfiedLinkError: no tensorflow_cc in java.library.path`.  I have tried to also include those libraries: 
```
 {
          "maven": {"coordinates": "org.tensorflow:libtensorflow_jni:1.11.0"}
     },
```

          {
        "maven": {"coordinates": "org.tensorflow:libtensorflow:1.11.0"}
        },`
But I still get the same errors

**Comment by saudet** [comment]
You'll need libtensorflow_cc.so, and it's probably missing from your class path. I'm guessing that your build system is not able to put all the required JAR files in the class path. You'll need to figure out why that is...

**Comment by saudet** [comment]
@giorgiomondauto One way to work around this is to use Maven to create an uber JAR, and give that large JAR to your other buggy build system. If that still doesn't work though, please let me know!

**Comment by codievilky** [comment]
@saudet I have the same error in macos with m1 Apple Silicon.

**Comment by saudet** [comment]
TensorFlow doesn't support that platform, yet.
