### ISSUE TITLE
No LTO in java.library.path

### ISSUE THREAD

**Issue by ftomassetti** [bytedeco/javacpp-presets#315]
Running an example using gradle:

```
uildscript {
   ext.kotlin_version = '1.0.3'

   repositories {
     mavenCentral()
     maven {
        name 'JFrog OSS snapshot repo'
        url  'https://oss.jfrog.org/oss-snapshot-local/'
     }
     jcenter()
   }

   dependencies {
     classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
   }
}

apply plugin: 'kotlin'
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'antlr'

repositories {
  mavenLocal()
  mavenCentral()
  jcenter()
}

dependencies {
  antlr "org.antlr:antlr4:4.5.1"
  compile "org.antlr:antlr4-runtime:4.5.1"
  compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
  compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
  compile 'org.ow2.asm:asm-all:5.1'
  compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2'
  testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
  testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
  testCompile 'junit:junit:4.12'
}

configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}

generateGrammarSource {
    maxHeapSize = "64m"
    arguments += ['-package', 'me.tomassetti.langsandbox']
    outputDirectory = new File("generated-src/antlr/main/me/tomassetti/langsandbox".toString())
}
compileJava.dependsOn generateGrammarSource
sourceSets {
    generated {
        java.srcDir 'generated-src/antlr/main/'
    }
}
compileJava.source sourceSets.generated.java, sourceSets.main.java
compileKotlin.source sourceSets.generated.java, sourceSets.main.java, sourceSets.main.kotlin

clean{
    delete "generated-src"
}

idea {
    module {
        sourceDirs += file("generated-src/antlr/main")
    }
}
```

code:

```
package me.tomassetti.sandy.compiling

import org.bytedeco.javacpp.BytePointer
import org.bytedeco.javacpp.LLVM.*
import org.bytedeco.javacpp.PointerPointer

fun main(args: Array<String>) {
    val module = LLVMModuleCreateWithName("me.tomassetti.LLVMExample")
    // an array is a PointerPointer in the JavaCPP-Presets. Don't ask...
    val param_types = PointerPointer(LLVMInt32Type(), LLVMInt32Type())
    val ret_type = LLVMFunctionType(LLVMInt32Type(), param_types, 2, 0)
    val sum = LLVMAddFunction(module, "sum", ret_type)
    val entry = LLVMAppendBasicBlock(sum, "entry")
    val builder = LLVMCreateBuilder()
    LLVMPositionBuilderAtEnd(builder, entry)
    val tmp = LLVMBuildAdd(builder, LLVMGetParam(sum, 0), LLVMGetParam(sum, 1), "tmp")
    LLVMBuildRet(builder, tmp)
    var error = BytePointer()
    LLVMVerifyModule(module, LLVMAbortProcessAction, error)
    LLVMDisposeMessage(error)

    var engine = LLVMExecutionEngineRef()
    error = BytePointer()
    LLVMLinkInMCJIT()
    LLVMInitializeNativeTarget()
    if (LLVMCreateExecutionEngineForModule(engine, module, error) != 0) {
        print(error)
    }
    if (!error.isNull) {
        print(error)
        LLVMDisposeMessage(error)
    }
}
package me.tomassetti.sandy.compiling

import org.bytedeco.javacpp.BytePointer
import org.bytedeco.javacpp.LLVM.*
import org.bytedeco.javacpp.PointerPointer

fun main(args: Array<String>) {
    val module = LLVMModuleCreateWithName("me.tomassetti.LLVMExample")
    // an array is a PointerPointer in the JavaCPP-Presets. Don't ask...
    val param_types = PointerPointer(LLVMInt32Type(), LLVMInt32Type())
    val ret_type = LLVMFunctionType(LLVMInt32Type(), param_types, 2, 0)
    val sum = LLVMAddFunction(module, "sum", ret_type)
    val entry = LLVMAppendBasicBlock(sum, "entry")
    val builder = LLVMCreateBuilder()
    LLVMPositionBuilderAtEnd(builder, entry)
    val tmp = LLVMBuildAdd(builder, LLVMGetParam(sum, 0), LLVMGetParam(sum, 1), "tmp")
    LLVMBuildRet(builder, tmp)
    var error = BytePointer()
    LLVMVerifyModule(module, LLVMAbortProcessAction, error)
    LLVMDisposeMessage(error)

    var engine = LLVMExecutionEngineRef()
    error = BytePointer()
    LLVMLinkInMCJIT()
    LLVMInitializeNativeTarget()
    if (LLVMCreateExecutionEngineForModule(engine, module, error) != 0) {
        print(error)
    }
    if (!error.isNull) {
        print(error)
        LLVMDisposeMessage(error)
    }
}
```

I get this:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniLLVM in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.LLVM.<clinit>(LLVM.java:10)
	at me.tomassetti.sandy.compiling.LlvmKt.main(Llvm.kt:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.UnsatisfiedLinkError: no LTO in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	at org.bytedeco.javacpp.Loader.load(Loader.java:483)
	... 8 more
```

**Comment by ftomassetti** [comment]
I am not sure if this could be the cause of it but opening the jar it seems that just 2 of the 5 so files are marked as executable:

![selection_406](https://cloud.githubusercontent.com/assets/439078/20075332/12de62a4-a534-11e6-904c-f8e1dddf5646.png)

**Comment by saudet** [comment]
It doesn't matter what their mode is. I think a few things got fixed with the move to CMake, so try again with LLVM 3.9.0 and let me know if you still encounter that issue. Thanks!

**Comment by ftomassetti** [comment]
the version with LLVM 3.9.0 seems to not have been released yet

**Comment by ftomassetti** [comment]
I tried to build but I get an error about the Python version. It complaints python is too old but `python --version` is telling me the version is 2.7

```
-- Building with -fPIC
CMake Error at CMakeLists.txt:488 (message):
  Python 2.7 or newer is required


-- Configuring incomplete, errors occurred!
See also "/home/federico/repos/javacpp-presets/llvm/cppbuild/linux-x86_64/llvm-3.9.0.src/build/CMakeFiles/CMakeOutput.log".
See also "/home/federico/repos/javacpp-presets/llvm/cppbuild/linux-x86_64/llvm-3.9.0.src/build/CMakeFiles/CMakeError.log".
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by ftomassetti** [comment]
Solved the python issue (by changing the CMakeCache file) BUT also building master the LTO issue is still there

**Comment by saudet** [comment]
I see, you're not using the `llvm-platform` artifact. You'll need to either use that or add the platform-specific artifact manually. On Linux that should be:
```
  compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2:linux-x86_64'
```

**Comment by ftomassetti** [comment]
With this:
```
  compile 'org.bytedeco:javacpp:1.2.4'
  compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2'
```
I have the same error.

Using just:
```
compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2:linux-x86_64'
```
it does not find the LLVM classes and do not compile. Same thing with:
```
  compile 'org.bytedeco:javacpp:1.2.4'
  compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2:linux-x86_64'
```

Should I use:
```
  compile 'org.bytedeco:javacpp:1.2.4'
  compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2'
  compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2:linux-x86_64'
```

**Comment by saudet** [comment]
Yes, that's what is written in the README.md file.

**Comment by saudet** [comment]
But let me know if that doesn't work! Thanks

**Comment by phase** [comment]
Using all three solved the problem for me!
