### ISSUE TITLE
Xiaomi Mi Note: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by vadimasadchi** [bytedeco/javacpp-presets#334]
On Xiaomi Mi Note (Android 4.4.4) I'm always getting error above. MultiDEX is enabled and I've already tried most of solutions of similar problems(manual setup, copying *.so files to libJni, different versions of build tools and lib versions). I'm trying to use ffmpeg and it works everywhere except this phone. Full log here(I think first line is most significant):

```
E/dalvikvm: dlopen("/data/app-lib/com.mydomain.myapp/libjniavutil.so") failed: dlopen failed: cannot locate symbol "av_log_format_line" referenced by "libjniavutil.so"...
W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/bytedeco/javacpp/avutil;
I/dalvikvm: Rejecting re-init on previously-failed class Lorg/bytedeco/javacpp/avutil; v=0x0
I/dalvikvm: Rejecting re-init on previously-failed class Lorg/bytedeco/javacpp/avutil; v=0x0
W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lorg/bytedeco/javacpp/avcodec$AVPacket;
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41738d58)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mydomain.myapp, PID: 28808
                  java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
                      at org.bytedeco.javacpp.Loader.load(Loader.java:590)
                      at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                      at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1559)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
                      at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
```

and this is part of my build.gradle:
```   
compile group: 'org.bytedeco', name: 'javacpp', version: '1.3'
compile(group: 'org.bytedeco', name: 'javacv-platform', version: '1.3') {
  exclude group: 'org.bytedeco.javacpp-presets'
}
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2', classifier: 'android-x86'
```

**Comment by saudet** [comment]
Sounds like a problem cause by a bad device. Please use ReLinker:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by vadimasadchi** [comment]
Thanks @saudet! It works
