### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by darshit7** [bytedeco/javacpp-presets#342]
Hi,
I have also go through bug number #133 
I have also copied .so of javacv, javacpp, ffmpeg-android-x86 and ffmpeg-android-arm file in respective armeabi-v7a and x86 folders but still got this error.
I am using Android Studio 2.2
Here is my app module gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"
    defaultConfig {
        applicationId "com.example.dp.facialemotionalyzer"
        minSdkVersion 21
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    // Use prebilt *.so. Don't run ndk-build
    sourceSets {
        main {
            jniLibs.srcDirs = ["src/main/jniLibs"]
        }
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support:support-v13:24.2.1'
    compile 'com.android.support:recyclerview-v7:24.2.1'
    testCompile 'junit:junit:4.12'
    compile project(':dlib')
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')
    compile files('libs/javacv-platform.jar')
    compile files('libs/ffmpeg-android-x86.jar')
    compile files('libs/ffmpeg-android-arm.jar')
    compile files('libs/ffmpeg-platform.jar')
}
```
and Logcat error

```
2-24 10:02:18.220 6423-6747/com.example.dp.facialemotionalyzer D/---: org.bytedeco.javacv.FFmpegFrameGrabber@57fe82
12-24 10:02:18.228 6423-6747/com.example.dp.facialemotionalyzer I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
                                                                       
                                                                       --------- beginning of crash
12-24 10:02:18.228 6423-6747/com.example.dp.facialemotionalyzer E/AndroidRuntime: FATAL EXCEPTION: Thread-65048
                                                                                  Process: com.example.dp.facialemotionalyzer, PID: 6423
                                                                                  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                      at java.lang.Class.classForName(Native Method)
                                                                                      at java.lang.Class.forName(Class.java:324)
                                                                                      at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                                                      at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                                      at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
                                                                                      at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:391)
                                                                                      at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:385)
                                                                                      at com.example.dp.facialemotionalyzer.service.VideoAnalyzerService$1.run(VideoAnalyzerService.java:69)
                                                                                      at java.lang.Thread.run(Thread.java:818)

```
What else I am missing?

**Comment by saudet** [comment]
This is probably caused by a bad device. Please try to use ReLinker:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
