### ISSUE TITLE
New preset LiquidFun: can't find .dylib on macosx

### ISSUE THREAD

**Issue by floybix** [bytedeco/javacpp-presets#351]
Hi,

I'm working on a new preset for [LiquidFun](https://github.com/google/liquidfun)

Here it is so far: https://github.com/floybix/javacpp-presets/tree/liquidfun/liquidfun

The problem I am stuck on is that it can't find the native lib unless I install it on the global system path.

This comes up when running the minimal example:

```
$ mvn clean compile exec:java
...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: no jniliquidfun in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
	at org.bytedeco.javacpp.Loader.load(Loader.java:750)
	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
	at org.bytedeco.javacpp.liquidfun.<clinit>(liquidfun.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:712)
	at org.bytedeco.javacpp.Loader.load(Loader.java:657)
	at org.bytedeco.javacpp.liquidfun$b2World.<clinit>(liquidfun.java:3494)
	at LFTest.main(LFTest.java:6)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: /Users/felix/.javacpp/cache/liquidfun-1.1.0-1.3.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniliquidfun.dylib: dlopen(/Users/felix/.javacpp/cache/liquidfun-1.1.0-1.3.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniliquidfun.dylib, 1): Library not loaded: libliquidfun.2.3.0.dylib
  Referenced from: /Users/felix/.javacpp/cache/liquidfun-1.1.0-1.3.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniliquidfun.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:925)
	... 15 more
```

Since the error mentions the `.javacpp/cache` path, I can confirm that the native lib is in there:

```
$ ls -l /Users/felix/.javacpp/cache/liquidfun-1.1.0-1.3.1-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/
total 2160
-rw-r--r--  1 felix  staff  743536  4 Jan 16:58 libjniliquidfun.dylib
-rw-r--r--  1 felix  staff  354064  4 Jan 16:58 libliquidfun.2.3.0.dylib
lrwxr-xr-x  1 felix  staff      24  3 Jan 20:01 libliquidfun.dylib -> libliquidfun.2.3.0.dylib
```

and when I copy `libliquidfun.2.3.0.dylib` to `/usr/local/lib/` it works fine.

I have no idea how to make progress on this, any hints?

**Comment by saudet** [comment]
We often need to rename the library with an `@rpath` for the libraries on that platform. You'll find various examples of that in the presets:
https://github.com/bytedeco/javacpp-presets/search?utf8=%E2%9C%93&q=rpath&type=Code
Pick the method that applies best to your library and use that.

**Comment by floybix** [comment]
Thanks, that worked!
