### ISSUE TITLE
couldn't find "libjniavutil.so"

### ISSUE THREAD

**Issue by tajj** [bytedeco/javacpp-presets#448]
Hello, 

I'm attempting to use the facebook live api with ffmpeg for my android app. I was modeling my live stream activity after RecordActivity in samples. I am getting this couldn't find "libjniavutil.so" error, even though when I run a search in  android studio I can find the file. Not sure how to resolve this issue.

`/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.example.mapdemo, PID: 4398
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.example.mapdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.mapdemo-1/lib/arm64, /data/app/com.example.mapdemo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libjniavutil.so"
  at java.lang.Runtime.loadLibrary0(Runtime.java:972)
 at java.lang.System.loadLibrary(System.java:1567)
  at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
at org.bytedeco.javacpp.Loader.load(Loader.java:438)
 at org.bytedeco.javacpp.Loader.load(Loader.java:381)
  at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
   at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:400)
 at org.bytedeco.javacpp.Loader.load(Loader.java:413)
 at org.bytedeco.javacv.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:91)
at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:112)
 at com.example.mapdemo.StreamingActivity.initRecorder(StreamingActivity.java:176)
at com.example.mapdemo.StreamingActivity.startRecording(StreamingActivity.java:281)
 at com.example.mapdemo.StreamingActivity.onClick(StreamingActivity.java:544)
at android.view.View.performClick(View.java:6261)
 at android.widget.TextView.performClick(TextView.java:11157)
at android.view.View$PerformClick.run(View.java:23748)
 at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by saudet** [comment]
Please try again with the latest version.

**Comment by tajj** [comment]
With the latest version of.... @saudet

**Comment by tajj** [comment]
What are you referring to when you say the latest version?  @saudet

**Comment by saudet** [comment]
The latest versions of every dependencies with "org.bytedeco" in the group.

**Comment by tajj** [comment]
Hmm...now the activity for live streaming is not even opening and I get an error that says unable to start activity...Fail to connect camera service

**Comment by saudet** [comment]
This is probably caused by a buggy device. Please follow the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
