### ISSUE TITLE
loaded dependency walker

### ISSUE THREAD

**Issue by Aaisha31** [bytedeco/javacpp-presets#474]
As I am working on IntelliJ Idea using maven, running the examples, i was not able to load openblas, so i followed the steps mentioned at: https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows#using-dependency-walker, but now getting an error:
Exception in thread "main" java.lang.NullPointerException
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:367)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:349)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:316)
	at org.deeplearning4j.examples.dataexamples.CSVExample.main(CSVExample.java:41)

Kindly help.

**Comment by saudet** [comment]
Could you try with Maven on the command line?

**Comment by Aaisha31** [comment]
No.. I am executing it on IntelliJ idea.

**Comment by Aaisha31** [comment]
please help, have included all the jar files as well.

**Comment by saudet** [comment]
Like I said, please try with Maven on the command line. Do not use IntelliJ.

**Comment by Aaisha31** [comment]
I am getting the same error on command line as well.
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Aaisha\.javacpp\cache\dl4j-examples-0.9.1-bin.jar\org\bytedeco\javacpp\windows-x86_64\jniopenblas.dll: The specified procedure could not be found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:956)
        ... 17 more

**Comment by saudet** [comment]
Yes, ok, now run Dependency Walker on C:\Users\Aaisha.javacpp\cache\dl4j-examples-0.9.1-bin.jar\org\bytedeco\javacpp\windows-x86_64\jniopenblas.dll

**Comment by saudet** [comment]
Given the lack of feedback, I assume you have resolved the issue, but could you please let me know of your findings so I can make any necessary corrections to JavaCPP? Thank you!

**Comment by saudet** [comment]
I've also fixed a bunch of loading issues with JavaCPP, OpenBLAS, and MKL, so everything should work well with the newly released version 1.4,

**Comment by Aaisha31** [comment]
Thanku so much for your kind help.
