### ISSUE TITLE
Openblas of presetes 1.4 not found on OSX 10.11.6

### ISSUE THREAD

**Issue by gunther82** [bytedeco/javacpp-presets#506]
I'm trying to use the new presets 1.4 with javacv 1.4 as well, but when I try to instantiate caffe on a Macbook with OSX 10.11.6 I get this exception:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicaffe in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
	at org.bytedeco.javacpp.Loader.load(Loader.java:613)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.caffe.<clinit>(caffe.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.caffe$FloatNet.<clinit>(caffe.java:23480)
	...
Caused by: java.lang.UnsatisfiedLinkError: /Users/claudio/.javacpp/cache/caffe-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjnicaffe.dylib: dlopen(/Users/claudio/.javacpp/cache/caffe-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjnicaffe.dylib, 1): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/claudio/.javacpp/cache/caffe-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjnicaffe.dylib
  Reason: image not found
```

**Comment by saudet** [comment]
What does your pom.xml file look like?

**Comment by saudet** [comment]
What does the content of your ~/.javacpp/cache/ looks like?

**Comment by gunther82** [comment]
The content of that directory was:

> gioacchino:.javacpp claudio$ ll cache/
total 0
drwxr-xr-x  3 claudio  staff  102 20 Dic  2016 caffe-macosx-x86_64.jar
drwxr-xr-x  3 claudio  staff  102 27 Feb  2017 ffmpeg-macosx-x86_64.jar
drwxr-xr-x  3 claudio  staff  102 21 Set 17:41 hdf5-macosx-x86_64.jar
drwxr-xr-x  3 claudio  staff  102 21 Mar  2017 libdc1394-macosx-x86_64.jar
drwxr-xr-x  4 claudio  staff  136 21 Set 17:41 libmkl_rt.dylib
drwxr-xr-x  3 claudio  staff  102 20 Dic  2016 openblas-macosx-x86_64.jar
drwxr-xr-x  3 claudio  staff  102 20 Dic  2016 opencv-macosx-x86_64.jar

then I renamed it and run again my Eclipse project, and it recreated it with this content:

> gioacchino:.javacpp claudio$ ll cache/
total 0
drwxr-xr-x  3 claudio  staff  102 19 Gen 14:28 caffe-macosx-x86_64.jar
drwxr-xr-x  3 claudio  staff  102 19 Gen 14:30 libmkl_rt.dylib
drwxr-xr-x  3 claudio  staff  102 19 Gen 14:28 openblas-macosx-x86_64.jar

The referenced libraries in my project are [these](https://www.dropbox.com/s/m6166wqdmok8e1w/Screenshot%202018-01-19%2014.35.13.png?dl=0)

**Comment by saudet** [comment]
Please do a `find` on that to list all the files recursively.

**Comment by saudet** [comment]
It looks like you have MKL installed, but it's not functional for some reason. Set the

**Comment by saudet** [comment]
You're using an old version of the presets. Please upgrade to version 1.4.

**Comment by saudet** [comment]
You're using an old version of JavaCPP, actually. Please upgrade to version 1.4.
