### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by linson007** [bytedeco/javacpp-presets#55]
java -cp "/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.35.x86_64/jre/lib/ext/*:" caffe train -solver ../caffe-master/examples/mnist/lenet_solver.prototxt

while running this command,
i get following error..

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1709)
        at java.lang.Runtime.loadLibrary0(Runtime.java:844)
        at java.lang.System.loadLibrary(System.java:1051)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
        at org.bytedeco.javacpp.Loader.load(Loader.java:411)
        at org.bytedeco.javacpp.Loader.load(Loader.java:354)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at org.bytedeco.javacpp.Loader.load(Loader.java:386)
        at org.bytedeco.javacpp.Loader.load(Loader.java:354)
        at org.bytedeco.javacpp.caffe$SolverParameter.<clinit>(caffe.java:1704)
        at caffe$2.command(caffe.java:177)
        at caffe.main(caffe.java:391)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp4072173147710/libjniopencv_core.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/javacpp4072173147710/libjniopencv_core.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1778)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1674)
        at java.lang.Runtime.load0(Runtime.java:790)
        at java.lang.System.load(System.java:1025)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:525)
        ... 10 more

Whether it is related to environmental issue or running isssue??

I am using Centos 6.7 with GLIBC_2.12.
Whether i need to upgrade glibc ??

**Comment by saudet** [comment]
No, it means you'll need to build from source, see #22.
