### ISSUE TITLE
LiquidFun issue

### ISSUE THREAD

**Issue by ShengPengYu** [bytedeco/javacpp-presets#550]
When i want to build LiquidFun project and write a test class obey  the web guide(https://github.com/bytedeco/javacpp-presets/tree/master/liquidfun). 
There have an error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.javacpp.liquidfun
	at org.bytedeco.javacpp.Loader.load(Loader.java:916)
	at org.bytedeco.javacpp.Loader.load(Loader.java:879)
	at org.bytedeco.javacpp.liquidfun.<clinit>(liquidfun.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:938)
	at org.bytedeco.javacpp.Loader.load(Loader.java:879)
	at org.bytedeco.javacpp.liquidfun$b2World.<clinit>(liquidfun.java:3891)
	at demo.BallDemo.main(BallDemo.java:13)

**Comment by saudet** [comment]
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.javacpp.liquidfun

Marking as duplicate of #524 and #536

Please consider participating in the effort! Thanks for your interest

/cc @soylomass @nornagon
