### ISSUE TITLE
Project including tesseract runs successfully on local Windows, crashes on Ubuntu

### ISSUE THREAD

**Issue by j0rdanit0** [bytedeco/javacpp-presets#575]
Hi, I am trying to deploy a project that includes the tesseract-platform (see pom dependency below), which I develop from a Windows machine, **to an Ubuntu prod box**. When I run my project locally on Windows, it starts up correctly and correctly scans images for text. However, when I deploy the same project to the Ubuntu server, it blows up the first time I instantiate `new org.bytedeco.javacpp.tesseract.StringGenericVector()`, which I use to pass in Init() parameters. **I am unsure of whether this is an issue with the tesseract-platform dependency which I am including, or with my project setup**. Any help would be appreciated, thanks.

pom.xml:
```
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>tesseract-platform</artifactId>
            <version>4.0.0-beta.1-1.4.2-SNAPSHOT</version>
        </dependency>
```

Root of the stacktrace: (let me know if you'd like to see the full stacktrace)
```
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/tesseract-4.0.0-beta.1-1.4.2-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnitesseract.so: libgomp.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[na:1.8.0_171]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[na:1.8.0_171]
        at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_171]
        at java.lang.System.load(System.java:1086) ~[na:1.8.0_171]
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1204) ~[javacpp-1.4.2-SNAPSHOT.jar!/:4.0.0-beta.1-1.4.2-SNAPSHOT]
```

**Comment by saudet** [comment]
The build is now bundling `libgomp.so.1` so this should be fixed. Thanks for reporting and let me know if you encounter any other issues!
