### ISSUE TITLE
Compiling ffmpeg with custom flags and using along with the presets gives an error

### ISSUE THREAD

**Issue by ImGauravC** [bytedeco/javacpp-presets#61]
I'm basically trying to reduce the size of the binaries by disabling features I don't need. 
It works perfectly fine with enabling a few encoders, but when I try to enable only the decoders as below, the error throws up.

Compile flags; 
```
./configure --prefix=.. \
                --enable-shared \
                --enable-gpl \
                --enable-version3 \
                --enable-nonfree \
                --enable-runtime-cpudetect \
                --disable-iconv \
                --disable-libxcb \
                --disable-opencl \
                --disable-outdev=sdl \
                --disable-doc \
                --disable-htmlpages \
                --disable-manpages \
                --disable-podpages \
                --disable-txtpages \
                --disable-postproc \
                --disable-debug \
                --enable-optimizations \
                --disable-ffmpeg \
                --disable-ffprobe \
                --disable-ffserver \
                --disable-avdevice \
                --disable-debug \
                --disable-mmx \
                --enable-small \
                --enable-libx264 \
                --enable-cross-compile \
                --cross-prefix="$ANDROID_BIN-" \
                --ranlib="$ANDROID_BIN-ranlib" \
                --sysroot="$ANDROID_ROOT" \
--target-os=linux \
                --arch=arm \
                --extra-cflags="-I../include/ -DANDROID -fPIC -ffunction-sections -funwind-tables -fstack-protector -march=armv7-\
a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300" \
                --extra-ldflags="$ANDROID_ROOT/usr/lib/crtbegin_so.o -L../lib/ -L$ANDROID_CPP/libs/armeabi/ -nostdlib -Wl,--fix-c\
ortex-a8" \
                --extra-libs="-lgnustl_static -lgcc -ldl -lz -lm -lc" \
                --disable-symver \
                --disable-programs \
                --disable-encoders \
                --disable-decoders \
                --enable-encoder=libx264 \
                `#--enable-encoder=libx264rgb` \
                --enable-encoder=h264_qsv \
                --enable-encoder=pcm_s16le_planar \
                --enable-encoder=aac \
                --enable-decoder=h264 \
                --enable-decoder=nellymoser \
                --enable-decoder=aac \
                --enable-decoder=pcm_s16le_planar \

```

Error output

```
  890-940/? D/<package>﹕ Could not load the Frame Grabber
    <package>.utils.ffmpeg.FrameGrabber$Exception: Failed to load class <package>.utils.ffmpeg.CVFrameGrabber
            at <package>.utils.ffmpeg.CVFrameGrabber.tryLoad(CVFrameGrabber.java:168)
            at <package>.utils.Helpers$1.doInBackground(Helpers.java:927)
            at <package>.utils.Helpers$1.doInBackground(Helpers.java:923)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_dct_init" referenced by "libjniavcodec.so"...
            at java.lang.Runtime.loadLibrary(Runtime.java:371)
            at java.lang.System.loadLibrary(System.java:988)
            at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
            at org.bytedeco.javacpp.Loader.load(Loader.java:411)
            at org.bytedeco.javacpp.Loader.load(Loader.java:354)
            at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:13)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at org.bytedeco.javacpp.Loader.load(Loader.java:386)
            at <package>.utils.ffmpeg.CVFrameGrabber.tryLoad(CVFrameGrabber.java:159)
            at <package>.utils.Helpers$1.doInBackground(Helpers.java:927)
            at <package>.utils.Helpers$1.doInBackground(Helpers.java:923)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/<package>.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/<package>.debug-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
            at org.bytedeco.javacpp.Loader.load(Loader.java:402)
            at org.bytedeco.javacpp.Loader.load(Loader.java:354)
            at org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:13)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at org.bytedeco.javacpp.Loader.load(Loader.java:386)
            at <package>.utils.ffmpeg.CVFrameGrabber.tryLoad(CVFrameGrabber.java:159)
            at <package>.utils.Helpers$1.doInBackground(Helpers.java:927)
            at <package>.utils.Helpers$1.doInBackground(Helpers.java:923)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by saudet** [comment]
Did you also run `mvn install`?

**Comment by saudet** [comment]
I've noticed that those symbols disappear when we `--disable-fft` so I've removed the parsing of the corresponding header file `libavcodec/avfft.h` by default in version 1.1. That should fix this issue. Thanks for reporting!

**Comment by lmylr** [comment]
@saudet 
Why I can not use the FFmpegFrameFilter?
`java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.postproc
                                                                   at java.lang.Class.classForName(Native Method)
                                                                   at java.lang.Class.forName(Class.java:308)
                                                                   at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                                   at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                   at org.bytedeco.javacpp.avfilter.<clinit>(avfilter.java:17)
                                                                   at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:169)
                                                                   at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)`
