### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnifreenect2 in java.library.path

### ISSUE THREAD

**Issue by AAcquier** [bytedeco/javacpp-presets#612]
Hi everyone,
I am trying to run the example libfreenect2 (freenect2Example) but I get the error message that I am using at a title. I am on ubuntu using intellij IDEA and maven, the error message is as follow:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnifreenect2 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1225)
	at org.bytedeco.javacpp.Loader.load(Loader.java:983)
	at org.bytedeco.javacpp.Loader.load(Loader.java:882)
	at org.bytedeco.javacpp.freenect2.<clinit>(freenect2.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:941)
	at org.bytedeco.javacpp.Loader.load(Loader.java:898)
	at org.centre.insight.KinectV2.try1.Kinect2Frames.main(Kinect2Frames.java:37)
Caused by: java.lang.UnsatisfiedLinkError: no freenect2 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1225)
	at org.bytedeco.javacpp.Loader.load(Loader.java:968)
	... 7 more
```
and my maven  file looks as follows:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>Kinectv2Try1</groupId>
    <artifactId>Java4KinectV2</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/libfreenect2 -->
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>libfreenect2</artifactId>
            <version>0.2.0-1.4.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.bytedeco/javacv -->
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.4.2</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.1</version>
                <configuration>
                    <attach>true</attach>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
```
The issue happen on the first line of code:
```java
 Loader.load(org.bytedeco.javacpp.freenect2.class);
```
Thanks in advance for you feedback

**Comment by saudet** [comment]
Instead of `libfreenect2` or `javacv`, add a dependency on either `libfreenect2-platform` or `javacv-platform`.

**Comment by AAcquier** [comment]
Sorry to insist but how would I do that? I am new in java coding, I have more a web programming background

**Comment by AAcquier** [comment]
Okay got it
