### ISSUE TITLE
JavaCPP GpuMat class and CUDA support

### ISSUE THREAD

**Issue by Daniel-Alievsky** [bytedeco/javacpp-presets#656]
I tried to use GpuMat class, available in JavaCPP for many functions, But calling constructor
`new opencv_core.GpuMat(mat);`
leads to exception:

OpenCV Error: No CUDA support (The library is compiled without CUDA support) in throw_no_cuda, file C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.0\modules\core\include\opencv2/core/private.cuda.hpp, line 107
Exception in thread "main" java.lang.RuntimeException: C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.0\modules\core\include\opencv2/core/private.cuda.hpp:107: error: (-216) The library is compiled without CUDA support in function throw_no_cuda

There is the same problem with some photo functions like opencv_photo.nonLocalMeans, even while passing them ordinary Mat type.

What does go wrong here? If this class is declared, why it doesn't work? 

Then I tried to use the latest SNAPSHOT version with GPU:
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.4.4-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.0.0-1.4.4-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv</artifactId>
            <version>4.0.0-1.4.4-SNAPSHOT</version>
            <classifier>windows-x86_64-gpu</classifier>
        </dependency>

        <dependency>
            <groupId>net.algart.stare</groupId>
            <artifactId>stare-java</artifactId>
            <version>${net.algart.stare.version}</version>
        </dependency>

```
The message changed: 
Exception in thread "main" java.lang.RuntimeException: OpenCV(4.0.0) C:/projects/javacpp-presets/opencv/cppbuild/windows-x86_64-gpu/opencv-4.0.0/modules/core/src/cuda/gpu_mat.cu:116: error: (-217:Gpu API call) CUDA driver version is insufficient for CUDA runtime version in function '<unnamed>::DefaultAllocator::allocate'

Maybe, you added CUDA support in jars in last version, but it works not for all drivers? My video is NVIDIA GeForce GTX 770M, not too old. How can I check, is it possible to use GpuMat, and switch to usual UMat processing? Your functions opencv_core.haveOpenCL()  and opencv_core.useOpenCL() return true; what else should I check?

**Comment by saudet** [comment]
Just like the error says, it doesn't look like those functions are implemented for CUDA. If you can confirm upstream that they should work with `GpuMat` though, please let me know, thanks!

**Comment by Daniel-Alievsky** [comment]
Ok, it seems that GaussianBlur do not support GpuMat version, though it is declared in your code.
I tried to used another function, that seems to be oriented to CUDA support - according the previous error message "CUDA driver version is insufficient for CUDA runtime version"
I tried to call opencv_cudaimgproc.bilateralFilter:
```
final opencv_core.GpuMat gpuMat = new opencv_core.GpuMat(mat.rows(), mat.cols(),mat.type());
mat.copyTo(gpuMat);
opencv_cudaimgproc.bilateralFilter(gpuMat, gpuMat, 7, 32.0f, 5.0f);

```
Now I see already Java linkage error message:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_cudaarithm in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1255)
	at org.bytedeco.javacpp.Loader.load(Loader.java:996)
	at org.bytedeco.javacpp.Loader.load(Loader.java:888)
	at org.bytedeco.javacpp.opencv_cudaarithm.<clinit>(opencv_cudaarithm.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.javacpp.Loader.load(Loader.java:888)
	at org.bytedeco.javacpp.opencv_cudaimgproc.<clinit>(opencv_cudaimgproc.java:15)
	at com.siams.stare.extensions.javacpp.opencv.SimpleJavaCPPOpenCV.main(SimpleJavaCPPOpenCV.java:41)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Daniel\.javacpp\cache\opencv-4.0.0-1.4.4-20181203.070338-80-windows-x86_64-gpu.jar\org\bytedeco\javacpp\windows-x86_64-gpu\jniopencv_cudaarithm.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1235)
	... 9 more

```
Did I forget anything in my pom dependencies? It seems that linkage error should not occur while using correct maven library.

**Comment by saudet** [comment]
Maybe, but could you first check which DLL it's looking for:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by Daniel-Alievsky** [comment]
Thank you. I've added to my test the following code (according your link):
```
try {
... (my previous code)   
} catch (UnsatisfiedLinkError e) {
    e.printStackTrace();
    String path = Loader.cacheResource(opencv_cudaimgproc.class, "windows-x86_64-gpu/jniopencv_cudaarithm.dll").getPath();
   new ProcessBuilder("D:\\Dependencies_x64_Release\\DependenciesGui.exe ", path).start().waitFor();
}

```
The screenshot of the result is attached
![dependenciesgui](https://user-images.githubusercontent.com/2530557/49613839-45c70a80-f9b1-11e8-92a9-db5681c7b509.png)
Can I do something else for you?

**Comment by saudet** [comment]
So, it's not reporting any missing DLLs?

**Comment by Daniel-Alievsky** [comment]
Samuel, I am not familiar with this utility. It seems that there are problems with first 2 DLLs opencv_cudaarithm400 and opencv_cuda400 - incorrect checksum, but I don't know why.
Below is the simplest test illustrating this problem:

```
public final class JavaCPPOpenCV40LinkageProblem {
    public static void main(String[] args) throws Exception {
        try {
            if (args.length == 0) {
                System.out.printf("Usage: %s source_image%n", JavaCPPOpenCV40LinkageProblem.class);
                return;
            }
            final String sourceFile = args[0];
            final opencv_core.Mat mat = opencv_imgcodecs.imread(sourceFile);
            final opencv_core.GpuMat gpuMat = new opencv_core.GpuMat(mat.rows(), mat.cols(), mat.type());
            mat.copyTo(gpuMat);
            opencv_cudaimgproc.bilateralFilter(gpuMat, gpuMat, 7, 32.0f, 5.0f);
            // - does not work yet
        } catch (UnsatisfiedLinkError e) {
            e.printStackTrace();
            String path = Loader.cacheResource(opencv_cudaimgproc.class, 
                "windows-x86_64-gpu/jniopencv_cudaarithm.dll").getPath();
            new ProcessBuilder("D:\\Dependencies_x64_Release\\DependenciesGui.exe ", path)
                .start().waitFor();
        }
    }
}

```

Stacktrace:

java.lang.UnsatisfiedLinkError: no jniopencv_cudaarithm in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1255)
	at org.bytedeco.javacpp.Loader.load(Loader.java:996)
	at org.bytedeco.javacpp.Loader.load(Loader.java:888)
	at org.bytedeco.javacpp.opencv_cudaarithm.<clinit>(opencv_cudaarithm.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.javacpp.Loader.load(Loader.java:888)
	at org.bytedeco.javacpp.opencv_cudaimgproc.<clinit>(opencv_cudaimgproc.java:15)
	at com.siams.stare.extensions.javacpp.opencv.JavaCPPOpenCV40LinkageProblem.main(JavaCPPOpenCV40LinkageProblem.java:20)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Daniel\.javacpp\cache\opencv-4.0.0-1.4.4-20181206.124250-97-windows-x86_64-gpu.jar\org\bytedeco\javacpp\windows-x86_64-gpu\jniopencv_cudaarithm.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1235)
	... 9 more

**Comment by Daniel-Alievsky** [comment]
I used the following 3 dependencies:
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.4.4-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.0.0-1.4.4-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv</artifactId>
            <version>4.0.0-1.4.4-SNAPSHOT</version>
            <classifier>windows-x86_64-gpu</classifier>
        </dependency>

```

**Comment by saudet** [comment]
Well, if you figure out what it's looking for, let me know and we'll fix
it! Thanks

**Comment by Daniel-Alievsky** [comment]
Sorry for my English, I didn't understand. Does this bug reproduce on your computers?

**Comment by saudet** [comment]
No, it works fine.

**Comment by AknurAsylkhankyzy** [comment]
I had the same problem, you just need to replace the
 import org.bytedeco.javacpp.opencv_cudaimgproc;
to this: 
 import org.bytedeco.javacpp.opencv_imgproc.*;

**Comment by lexNwimue** [comment]
AknurAsylkhankyzy, thanks so much for that info. I tried it and my code ran just fine too. :)
