### ISSUE TITLE
no opencv_cudaarithm in java.library.path

### ISSUE THREAD

**Issue by Peter-St** [bytedeco/javacpp-presets#692]
Hello,

From following code I'll get an java exception:

   Mat yuv = new Mat(480, 640, CV_8UC2, new BytePointer(frameData));
   Mat bgrImage = new Mat(480, 640, CV_8UC3);
   cvtColor(yuv, bgrImage, COLOR_YUV2BGR_NV21);        // <----------- (Here comes the error)

The log is:

Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no jniopencv_cudaarithm in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1043)
	at org.bytedeco.javacpp.Loader.load(Loader.java:935)
	at org.bytedeco.javacpp.opencv_cudaarithm.<clinit>(opencv_cudaarithm.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:994)
	at org.bytedeco.javacpp.Loader.load(Loader.java:935)
	at org.bytedeco.javacpp.opencv_cudaimgproc.<clinit>(opencv_cudaimgproc.java:15)
	at humer.kamera.ConvertStream.processReceivedVideoFrameYUYV422(ConvertStream.java:132)
	at humer.kamera.Kam$IsochronousStream.run(Kam.java:652)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_cudaarithm in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1021)
	... 9 more

My pom.xml:

 dependency
    groupId org.bytedeco /groupId  
        artifactId javacv-platform  /artifactId
        version 1.4.4 /version 
    /dependency 

Please help me out with this issue.

Peter

**Comment by saudet** [comment]
Make sure to add the -cuda artifacts as well:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#sample-usage
