### ISSUE TITLE
[GSL] NullPointerException when used with WorkStealingPool

### ISSUE THREAD

**Issue by yukoba** [bytedeco/javacpp-presets#697]
When I use ```gsl_integration_qagi()``` from ```Executors.newWorkStealingPool``` a NullPointerException is thrown. What is wrong? I cannot find the reason.

My environment:
- gsl-platform 2.5-1.4.4
- Windows 10
- Oracle Java 11.0.2

```
java.lang.NullPointerException
	at org.bytedeco.javacpp.gsl.gsl_integration_qagi(Native Method)
```

The test code. Please wait for a few minutes. This is a multithread problem and not always happens.

```Java
import org.bytedeco.javacpp.Pointer;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

import static org.bytedeco.javacpp.gsl.*;

public class GslTest {
    private static Double qagi(final Function<Double, Double> density) {
        gsl_function f = new gsl_function().function(new gsl_function.Function_double_Pointer() {
            @Override
            public double call(double x, Pointer params) {
                return density.apply(x);
            }
        });

        double[] result = new double[1];
        double[] abserr = new double[1];
        gsl_integration_workspace w = gsl_integration_workspace_alloc(1000);
        int err = gsl_integration_qagi(f, 0.0, 1e-9, 1000, w, result, abserr);
        gsl_integration_workspace_free(w);
        f.close();

        if (err == 0) {
            return result[0];
        } else {
            return Double.NaN;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Function<Double, Double> fn = x -> Math.exp(-x * x);

        ExecutorService executor = Executors.newWorkStealingPool(4);
        for (int i = 0; i < 1000 * 1000; i++) {
            executor.execute(() -> {
                try {
                    qagi(fn);
                } catch (Exception e) {
                    e.printStackTrace();
                    System.exit(-1);
                }
            });
        }
        executor.awaitTermination(1, TimeUnit.DAYS);
    }
}
```

**Comment by saudet** [comment]
It's possible that the function isn't thread-safe. Have you tried to call
it in a synchronized block?

**Comment by saudet** [comment]
Actually,  we shouldn't create more than one instance for each FunctionPointer. Try to move `f` into a field.

**Comment by saudet** [comment]
See issue #683 for more explanations about that.

**Comment by saudet** [comment]
And to pass around custom data, we can use the `Pointer params` and a `HashMap` as shown here, for example: https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L293

**Comment by yukoba** [comment]
> It's possible that the function isn't thread-safe

GSL says GSL is thread-safe.
https://www.gnu.org/software/gsl/manual/html_node/Thread_002dsafety.html

> Have you tried to call it in a synchronized block?

I changed to ```private synchronized static Double qagi(final Function<Double, Double> density) {``` but nothing is changed.

> we shouldn't create more than one instance for each FunctionPointer.

This is the answer.
If I give up multithread and modify like this there is no problem.

I tried to use ```Pointer params``` but it was impossible.
Also I tried to put qagiFn in a ThreadLocal but it was impossible too.
JavaCPP callback is not thread-safe.

```Java
import org.bytedeco.javacpp.Pointer;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

import static org.bytedeco.javacpp.gsl.*;

public class GslTest {
    private static Function<Double, Double> qagiFn;

    private static gsl_function qagiCallback = new gsl_function().function(new gsl_function.Function_double_Pointer() {
        @Override
        public double call(double x, Pointer params) {
            return qagiFn.apply(x);
        }
    });

    public static Double qagi(Function<Double, Double> density) {
        double[] result = new double[1];
        double[] abserr = new double[1];
        gsl_integration_workspace w = gsl_integration_workspace_alloc(1000);
        int err;
        synchronized (GslTest.class) {
            qagiFn = density;
            err = gsl_integration_qagi(qagiCallback, 0.0, 1e-9, 1000, w, result, abserr);
        }
        gsl_integration_workspace_free(w);

        if (err == 0) {
            return result[0];
        } else {
            return Double.NaN;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        ExecutorService executor = Executors.newWorkStealingPool();
        for (int i = 0; i < 1000 * 1000; i++) {
            Function<Double, Double> fn = i % 2 == 0 ? (x -> Math.exp(-x * x)) : (x -> Math.exp(-Math.abs(x)));
            executor.execute(() -> {
                try {
                    qagi(fn);
                } catch (Exception e) {
                    e.printStackTrace();
                    System.exit(-1);
                }
            });
        }
        executor.awaitTermination(1, TimeUnit.DAYS);
    }
}
```

**Comment by yukoba** [comment]
In short,

FunctionPointer limitations:
1. You cannot create 2 FunctionPointers from 1 Java function.
2. You cannot use a FunctionPointer callback simultaneously. FunctionPointer callback is not thread-safe.

**Comment by saudet** [comment]
We can't use more than one instance of the same subclass at the same time,
but we can use the same instance from multiple threads. That's fine and it
works without issue in JavaCV, for example.

**Comment by yukoba** [comment]
> we can use the same instance from multiple threads.

This code also creates NullPointerException. Why?

I used ```ConcurrentHashMap<Pointer, Function<Double, Double>>``` and get the Function from there. 
Does ```qagiCallback.params(pointer)``` create a new instance?

```
java.lang.NullPointerException
	at org.bytedeco.javacpp.gsl.gsl_integration_qagi(Native Method)
```

```Java
import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacpp.Pointer;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

import static org.bytedeco.javacpp.gsl.*;

public class GslTest3 {
    private static ConcurrentHashMap<Pointer, Function<Double, Double>> qagiFnMap = new ConcurrentHashMap<>();

    private static gsl_function qagiCallback = new gsl_function().function(new gsl_function.Function_double_Pointer() {
        @Override
        public double call(double x, Pointer params) {
            return qagiFnMap.get(params).apply(x);
        }
    });

    public static Double qagi(Function<Double, Double> density) {
        double[] result = new double[1];
        double[] abserr = new double[1];
        gsl_integration_workspace w = gsl_integration_workspace_alloc(1000);
        int err;
        Pointer pointer = new BytePointer(1L);
        synchronized (GslTest3.class) {
            qagiFnMap.put(pointer, density);
            err = gsl_integration_qagi(qagiCallback.params(pointer), 0.0, 1e-9, 1000, w, result, abserr);
        }
        gsl_integration_workspace_free(w);

        if (err == 0) {
            return result[0];
        } else {
            return Double.NaN;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        ExecutorService executor = Executors.newWorkStealingPool();
        for (int i = 0; i < 1000 * 1000; i++) {
            Function<Double, Double> fn = i % 2 == 0 ? (x -> Math.exp(-x * x)) : (x -> Math.exp(-Math.abs(x)));
            executor.execute(() -> {
                try {
                    qagi(fn);
                } catch (Exception e) {
                    e.printStackTrace();
                    System.exit(-1);
                }
            });
        }
        executor.awaitTermination(1, TimeUnit.DAYS);
    }
}
```

**Comment by saudet** [comment]
You're not keeping the instance of Function_double_Pointer in a field
somewhere, so it's probably getting garbage collected.

**Comment by yukoba** [comment]
> so it's probably getting garbage collected.

I see! This is the answer. Thank you!!

```Java
import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacpp.Pointer;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

import static org.bytedeco.javacpp.gsl.*;

public class GslTest3 {
    private static final ConcurrentHashMap<Pointer, Function<Double, Double>> qagiFnMap = new ConcurrentHashMap<>();

    private static final gsl_function.Function_double_Pointer fnpointer = new gsl_function.Function_double_Pointer() {
        @Override
        public double call(double x, Pointer params) {
            return qagiFnMap.get(params).apply(x);
        }
    };

    public static Double qagi(Function<Double, Double> density) {
        double[] result = new double[1];
        double[] abserr = new double[1];
        gsl_integration_workspace w = gsl_integration_workspace_alloc(1000);
        Pointer pointer = new BytePointer(1L);
        qagiFnMap.put(pointer, density);
        int err = gsl_integration_qagi(new gsl_function().function(fnpointer).params(pointer),
                0.0, 1e-9, 1000, w, result, abserr);
        qagiFnMap.remove(pointer);
        gsl_integration_workspace_free(w);

        if (err == 0) {
            return result[0];
        } else {
            return Double.NaN;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        ExecutorService executor = Executors.newWorkStealingPool();
        for (int i = 0; i < 1000 * 1000; i++) {
            Function<Double, Double> fn = i % 2 == 0 ? (x -> Math.exp(-x * x)) : (x -> Math.exp(-Math.abs(x)));
            executor.execute(() -> {
                try {
                    qagi(fn);
                } catch (Exception e) {
                    e.printStackTrace();
                    System.exit(-1);
                }
            });
        }
        executor.awaitTermination(1, TimeUnit.DAYS);
    }
}
```
