### ISSUE TITLE
Can I run this on Android?? ERROR: Platform "android-x86_64" not supported by class org.bytedeco.javacpp.onnx

### ISSUE THREAD

**Issue by SiR0N** [bytedeco/javacpp-presets#737]
Hello,

I try to make it running on Android but after some attempts I always get the same error: 

`java.lang.UnsatisfiedLinkError: Platform "android-x86_64" not supported by class org.bytedeco.javacpp.onnx`

(I have already tried with different platforms)
 I use SDK 28, NDK 17 and I built it by Gradle:

`implementation 'org.bytedeco.javacpp-presets:onnx-platform:1.3.0-1.4.4'`

is there any tutorial in Android? any tips?  should I add: `implementation 'org.bytedeco:javacpp:1.4.3'`?  I am newbie in the Android area.

**Comment by VertexC** [comment]
I got similar issue here 
```bash
java.lang.UnsatisfiedLinkError: Platform "android-arm64" not supported by class org.bytedeco.hdf5.global.hdf5
        at org.bytedeco.javacpp.Loader.load(Loader.java:984)
        at org.bytedeco.javacpp.Loader.load(Loader.java:963)
        at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<clinit>(Hdf5Archive.java:59)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.modelHdf5Filename(KerasModelBuilder.java:225)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:207)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:94)
        at bowenc.realtimeips.MainActivity$12.run(MainActivity.java:624)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by faisal3413** [comment]
Also, I think this library does not support 64 bit architecture, and now google requires apps to support 64 bit architecture starting from Aug 1, 2019.

otherwise android apps build with this library can't be published or update. Here is the snapshot of message by google.

![image](https://user-images.githubusercontent.com/20745843/60967907-7ba3e700-a324-11e9-8b36-e37396fd9aa1.png)
