### ISSUE TITLE
Py_SetPath(*org.bytedeco.numpy.global.numpy.cachePackages()) return NPE

### ISSUE THREAD

**Issue by nofurylion** [bytedeco/javacpp-presets#761]
Language : Kotlin
Build target : android 21+
Gradle : 
`implementation group: 'org.bytedeco', name: 'numpy', version: '1.16.4-1.5.1'`

Py_SetPath(*org.bytedeco.numpy.global.numpy.cachePackages()) return NPE
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getCanonicalPath()' on a null object reference
        at org.bytedeco.cpython.helper.python.Py_SetPath(python.java:46)
        at com.xx.drawing.PinchZoomPan$save$stat$1$1.invokeSuspend(PinchZoomPan.kt:415)
```

The content of  org.bytedeco.numpy.global.numpy.cachePackages is `[null, python3.7, python3.7/lib-dynload, python3.7/site-packages, null]`

**Comment by saudet** [comment]
Android isn't supported, yet.
