### ISSUE TITLE
Hand-built ONNX models are truncated

### ISSUE THREAD

**Issue by alannnna** [bytedeco/javacpp-presets#766]
I'm constructing ONNX models via javacpp-presets, but I'm getting errors when my message is past a certain size.

In the below code, `parseFrom` is imported from `com.google.protobuf.Any`, and `Builder` is my class that calls the javacpp-presets ONNX protobuf APIs. For completeness, it's in a gist [here](https://gist.github.com/alannnna/3a4b4231f5db6ff3959cffcd33de00d1).

This model works:
```
    val builder = Builder("Relu123456789012345678901234")
    builder.addConst("c", constData, inputShape)
    builder.addNode(Vector("c"), Vector("out"), "Relu")
    builder.addOutput("out")
    val model = builder.build()  // Returns a ModelProto
    parseFrom(model.SerializeAsString.getString.getBytes)
```
but this fails on the last line (the difference is that the string in the first line is one character longer):
```
    val builder = Builder("Relu1234567890123456789012345")
    builder.addConst("c", constData, inputShape)
    builder.addNode(Vector("c"), Vector("out"), "Relu")
    builder.addOutput("out")
    val model = builder.build()  // Returns a ModelProto
    parseFrom(model.SerializeAsString.getString.getBytes)
```
The specific error is:
```
[info]   com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message│
, the input ended unexpectedly in the middle of a field.  This could mean either that the inp│In [6]: len(x)
ut has been truncated or that an embedded message misreported its own length.                │Out[6]: 288
[info]   at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtoc│
olBufferException.java:86)                                                                   │In [7]: y = "08033A7E0A311207633132333435362208436F6E7374616E742A1C0A0576616C75652A1
[info]   at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.j│   ...: 00801100122040000EFBFBD3F420474657374EFBFBD01040A140A076331323334353612036F7
ava:1281)                                                                                    │   ...: 574220452656C75120953696E676C6541646462110A036F7574120A0A08080112040A0208016
[info]   at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java│   ...: A150A0763313233343536120A0A08080112040A02080142021006"
:935)                                                                                        │
[info]   at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:5│In [8]: len(y)
37)                                                                                          │Out[8]: 276
[info]   at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3│
.java:305)                                                                                   │In [9]: x = "08033A7F0A2B1201632208436F6E7374616E742A1C0A0576616C75652A1008011001220
[info]   at com.google.protobuf.Any.<init>(Any.java:114)                                     │   ...: 40000EFBFBD3F420474657374EFBFBD01040A0E0A016312036F7574220452656C75121C52656
[info]   at com.google.protobuf.Any.<init>(Any.java:75)                                      │   ...: C7531323334353637383930313233343536373839303132333462110A036F7574120A0A08080
[info]   at com.google.protobuf.Any$1.parsePartialFrom(Any.java:920)                         │   ...: 112040A0208016A0F0A0163120A0A08080112040A02080142021006"
[info]   at com.google.protobuf.Any$1.parsePartialFrom(Any.java:915)                         │
[info]   at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
```
The javacpp-presets docs show that ModelProto can take a size parameter; I have tried setting this to a large number but it doesn't solve the problem.

How can I construct a valid protobuf message using the javacpp-presets ONNX APIs?

cc @EmergentOrder

**Comment by EmergentOrder** [comment]
I was able to reproduce this issue, with the latest ONNX preset and a few version of protobuf . 
Also confirmed I cannot reproduce the same from Python.
I found someone else reporting this same issue here: https://groups.google.com/forum/#!topic/protobuf/hOJV6PrLwy0
and several others complaining of the same error, but not sure of the triggering condition.
So, it looks like a bug in https://github.com/protocolbuffers/protobuf/tree/master/java
