### ISSUE TITLE
Opecv OOM Error

### ISSUE THREAD

**Issue by penetest** [bytedeco/javacpp-presets#770]
code:
```
Mat pano = new Mat( row, col, CV_64FC1);
        DoubleIndexer idx = pano.createIndexer();
        for(int i = 0; i < lenght; i++){
            idx.put(i,Double.valueOf(fields.get(i).getValueAsString()));
        }
```
NOTE:  This code will run many times when run 

error infos:
```
java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = (40505M) > maxPhysicalBytes =(40411M)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:589)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:125)
	at org.bytedeco.javacpp.opencv_core.Mat.allocate(Native Method)
	at org.bytedeco.javacpp.opencv_core.Mat.<init>(Mat.java:232)
```

**Comment by saudet** [comment]
Try to deallocate pano manually once you're done with it.

**Comment by penetest** [comment]
@saudet  I have a try,it is not OK, how to do it.

**Comment by saudet** [comment]
Something like shown here:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by penetest** [comment]
I try to do it,but it is not ok. 
code as followings: 
```
 try (PointerScope scope = new PointerScope()) {
Mat pano = new Mat( row, col, CV_64FC1);
        DoubleIndexer idx = pano.createIndexer();
        for(int i = 0; i < lenght; i++){
            idx.put(i,Double.valueOf(fields.get(i).getValueAsString()));
        }
 scope.attach(pano);
  }
```

**Comment by saudet** [comment]
So the problem is likely somewhere else in your code...

**Comment by saudet** [comment]
Could you confirm that the OOM error still occurs if you remove these lines?

**Comment by penetest** [comment]
OOM error still occurs,the following is the complete code：

``` 
@Override
    protected void process(Record record, SingleLaneBatchMaker batchMaker) throws StageException {

        int width = record.get(conf.imageWidth).getValueAsInteger();
        int height = record.get(conf.imageHeight).getValueAsInteger();
        int row = height;
        int col = width;

        List<Field> fields = record.get(conf.imageDatas).getValueAsList();
        int lenght = fields.size();
//        Loader.load(opencv_core.class);
        try (PointerScope scope = new PointerScope()) {
            Mat pano = new Mat(row, col, CV_64FC1);
            DoubleIndexer idx = pano.createIndexer();
            for (int i = 0; i < lenght; i++) {
                idx.put(i, Double.valueOf(fields.get(i).getValueAsString()));
            }
                byte[] imagebytearray = new byte[(int) (height * width * pano.elemSize())];

                imencode(".png", pano, imagebytearray);

                BASE64Encoder encoder = new BASE64Encoder();
                String base64Img = encoder.encode(imagebytearray);

                record.set(conf.imageByteArray, Field.create(imagebytearray));
                record.set(conf.imageBase64, Field.create(base64Img));
   
            scope.attach(pano);
        }
        batchMaker.addRecord(record);
    }
```

**Comment by saudet** [comment]
You're accumulating a large amount of `byte[]` objects. That's probably what is using up all memory. If your profiler says otherwise, please let me know all the details it provides. Thanks!
