### ISSUE TITLE
Could not initialize class org.bytedeco.ffmpeg.global.avutil

### ISSUE THREAD

**Issue by lishoahua** [bytedeco/javacpp-presets#786]
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:44)
        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:340)

**Comment by lishoahua** [comment]
Loading class org.bytedeco.ffmpeg.global.avutil
Loading class org.bytedeco.ffmpeg.global.avutil
Loading library avutil
Failed to load for avutil@.56: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
Loading library jniavutil
Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
Loading class org.bytedeco.ffmpeg.global.avutil
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
        at org.bytedeco.javacpp.Loader.load(Loader.java:947)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:44)
        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:313)
        at Main.main(Main.java:23)

**Comment by saudet** [comment]
This just means JAR files are missing from the class path. Make sure to put all the JAR files in your class path and it will work.
