### ISSUE TITLE
no gfortran in java.library.path

### ISSUE THREAD

**Issue by netbrain** [bytedeco/javacpp-presets#791]
seems to be caused by `openblas/src/main/java/org/bytedeco/openblas/presets/openblas_nolapack.java`

which tried to preload gfortran. Does the host system need to have gfortran installed in order to use openblas?

**Comment by saudet** [comment]
No, it gets bundles, but there could be some bugs. Please provide more information!

**Comment by netbrain** [comment]
Sorry, yes I should have provided more info, so here goes.

I'm trying to create my own preset and I have the following mapping configuration:

```
@Properties(
        inherit = opencv_core.class,
        value = {
                @Platform(
                        value = "windows-x86_64",
                        includepath = {"../../dist/opencv-windows-static-x64-posix/include/opencv4"},
                        include = {"../../imbs-mt/imbs.hpp"}
                ),
                @Platform(
                        value = "linux-x86_64",
                        includepath = {"../../dist/opencv-linux-x64/include/opencv4"},
                        include = {"../../imbs-mt/imbs.hpp"}
                ),
        },
        target = "example.jni.imbs",
        global = "example.global.imbs"
)
public class Imbs implements InfoMapper {
    @Override
    public void map(InfoMap map) {
               map.put(new Info("cv::Vec3b").cast().pointerTypes("Point3i"));
    }
}
```

However when trying to use the library i get the "no gfortran in java.library.path" issue. And upon running the code in debug mode. I can see that the call that leads to the UnsatisfiedLinkException starts with the `static {Loader.load();}` in `openblas_noalpack`

The only library that imbs depends upon is opencv, so what's weird is that i don't get the issue when using opencv directly. Do i need to add some sort of preload or inhert on openblas im my preset?

**Comment by netbrain** [comment]
Here's with debug logging switched on:
```
> Task :Main.main()
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libgcc_s.so.1
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libquadmath.so.0
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libgfortran.so.4
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libopenblas_nolapack.so.0
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas_nolapack.so
Loading class org.bytedeco.openblas.global.openblas
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so.0
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas.so
Loading class org.bytedeco.opencv.global.opencv_core
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcudart.so.10.1
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcublasLt.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcublas.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcufft.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppc.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppial.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppicc.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppicom.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppidei.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppif.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppig.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppim.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppist.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppisu.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppitc.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnpps.so.10
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libgomp.so.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_cudev.so.4.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_core.so.4.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_imgproc.so.4.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libjniopencv_core.so
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.opencv_core.CvSlice
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
```

I see here that it's looking for @.3 or @.5. Im guessing this means the the number after the .so extension. however if i look inside the openblas-linux-x86_64 jar file i see libgfortran.so.4

**Comment by netbrain** [comment]
Renaming libgfortran.so.4 to libgfortran.so.3 did not do anything. just started complaining that @.4 was now missing. So im guessing this is expected behavior. and that it actually manages to load gfortran just not the so.3 and so.5.. But still should it really try to load the other libraries when it has successfully loaded another version?

`Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libgfortran.so.4`

**Comment by saudet** [comment]
It tries to load a few versions, but that's fine, that's not the problem. It loads `libgfortran.so.4` successfully and I don't see anything wrong with the log.

**Comment by netbrain** [comment]
Here's the complete log with my failing code aswell:

```
> Task :Main.main() FAILED
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libgcc_s.so.1
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libquadmath.so.0
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libgfortran.so.4
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libopenblas_nolapack.so.0
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas_nolapack.so
Loading class org.bytedeco.openblas.global.openblas
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so.0
Loading /home/netbrain/.javacpp/cache/openblas-0.3.6-1.5.1-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libjniopenblas.so
Loading class org.bytedeco.opencv.global.opencv_core
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcudart.so.10.1
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcublasLt.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcublas.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libcufft.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppc.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppial.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppicc.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppicom.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppidei.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppif.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppig.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppim.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppist.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppisu.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnppitc.so.10
Loading /home/netbrain/.javacpp/cache/cuda-10.1-7.6-1.5.1-linux-x86_64-redist.jar/org/bytedeco/cuda/linux-x86_64/libnpps.so.10
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libgomp.so.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_cudev.so.4.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_core.so.4.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_imgproc.so.4.1
Loading /home/netbrain/.javacpp/cache/opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar/org/bytedeco/opencv/linux-x86_64-gpu/libjniopencv_core.so
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas
Loading class org.bytedeco.opencv.global.opencv_core
Loading class org.bytedeco.opencv.opencv_core.CvSlice
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Registering org.bytedeco.opencv.opencv_core.CvSlice[address=0x7fa240799010,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fa240799010,deallocatorAddress=0x7fa1930d5f20]]
Registering org.bytedeco.opencv.opencv_core.CvSlice[address=0x7fa2407af970,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7fa2407af970,deallocatorAddress=0x7fa1930d5f20]]
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas
Loading class org.bytedeco.opencv.global.opencv_core
Loading class com.davo.swimeye3.jni.global.imbs
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas
Loading class org.bytedeco.opencv.global.opencv_core
Loading class example.global.imbs
Loading library gfortran
Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library gfortran
Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
Loading library jniimbs
Failed to load for jniimbs: java.lang.UnsatisfiedLinkError: no jniimbs in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniimbs in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1186)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
	at example.global.imbs.<clinit>(imbs.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1103)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1036)
	at example.imbs.BackgroundSubtractorIMBS.<clinit>(BackgroundSubtractorIMBS.java:19)
	at Main.main(Main.java:9)
Caused by: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1483)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1137)
	... 8 more
```

Any hints on how i can proceed debugging this?

**Comment by saudet** [comment]
It's not finding `jniimbs`. Where did you put that library?

**Comment by netbrain** [comment]
jniimbs is my preset. it's on the classpath in a jar file /home/netbrain/.m2/repository/example/imbs/imbs-mt/4.1.0-1.5.1/imbs-mt-4.1.0-1.5.1-linux-x86_64.jar!/libjniimbs.so

**Comment by saudet** [comment]
Well, it's not finding it, it doesn't even try to extract it. So there's something wrong with the class path.

**Comment by saudet** [comment]
Try to extract it manually with `Loader.cacheResource()` to see what happens.

**Comment by netbrain** [comment]
cacheResource("libjniimbs.so") seems to work fine, it returns the url to the file.

**Comment by saudet** [comment]
Try it with the other overload with your class.

**Comment by netbrain** [comment]
What do you mean specifically?

Could it have something to do with the libjniimbs.so file is at the root of the jar archive instead of within a folder?

**Comment by netbrain** [comment]
because line 1313 in Loader.java tries to use findResource on various subdirectories. e.g 

1. linux-x86_64-gpu/
2. //org/bytedeco/cuda/linux-x86_64/
3. linux-x86_64/

**Comment by saudet** [comment]
By default `Loader.load()` looks in the same package as your class, but that's fine if your class is in the default package. If you want to put it somewhere else though, it wasn't really designed for that, but it can still be done...

**Comment by netbrain** [comment]
traced the behavior of Loader.findResource() (which im guessing is called for all initial loads of library files) and the following is the filepaths it tried to use when resolving my library:

```
//org/bytedeco/cuda/linux-x86_64-gpu/libjniimbs.so
linux-x86_64-gpu/libjniimbs.so
//org/bytedeco/cuda/linux-x86_64/libjniimbs.so
linux-x86_64/libjniimbs.so
//org/bytedeco/cuda/linux-x86_64-gpu/libjniimbs.so
linux-x86_64-gpu/libjniimbs.so
//org/bytedeco/cuda/linux-x86_64/libjniimbs.so
linux-x86_64/libjniimbs.so
//org/bytedeco/cuda/linux-x86_64-gpu/libjniimbs.so
linux-x86_64-gpu/libjniimbs.so
//org/bytedeco/cuda/linux-x86_64/libjniimbs.so
linux-x86_64/libjniimbs.so
```

so from this i gather i need to add libjniimbs under a arch directory like "linux-x86_64" and then it should be able to load it. right?

**Comment by netbrain** [comment]
also seems theres an issue with it doing several identical lookups

**Comment by saudet** [comment]
> so from this i gather i need to add libjniimbs under a arch directory like "linux-x86_64" and then it should be able to load it. right?

Yes, that's where the build puts it by default and that's where it also tries to load it. If you do not change any of the defaults, it will work that way automatically. If you need to have it somewhere else, you'll need to do that kind of lookup manually.

> also seems theres an issue with it doing several identical lookups

What do you mean?

**Comment by netbrain** [comment]
three times on the same incvocation, findResource tried to lookup the same path.

But anyways, loading the library works fine now, but now it seems it's trying to link against my system library and not the the bytedeco opencv preset.

`Caused by: java.lang.UnsatisfiedLinkError: /home/netbrain/.javacpp/cache/imbs-mt-4.1.0-1.5.1-linux-x86_64.jar/linux-x86_64/libjniimbs.so: /usr/local/lib/libopencv_features2d.so.4.1: undefined symbol: _ZNK2cv9Algorithm4saveERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

Am i missing something in my mapping file?

**Comment by saudet** [comment]
> three times on the same incvocation, findResource tried to lookup the same path.

Not doing that here. This
```java
System.out.println(java.util.Arrays.toString(Loader.findResources(org.bytedeco.opencv.global.opencv_core.class, "linux-x86_64/libopencv_core.so.4.1")));
```
outputs only 1 element:
```
[jar:file:/home/saudet/.m2/repository/org/bytedeco/opencv/4.1.1-1.5.2-SNAPSHOT/opencv-4.1.1-1.5.2-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/opencv/linux-x86_64/libopencv_core.so.4.1]
```

> Am i missing something in my mapping file?

You're probably using an old version of GCC. You'll need at least GCC 6.x and it should be fine.

**Comment by netbrain** [comment]
set a breakpoint in Loadre.java:796 (version 1.5.1) and see what paths are being resolved, or tried.

and aslo see line 1313 which i believe is the culprit. That nested loop there doesn't take into account duplicate subdirs.


im running gcc version 7.4.0 (Debian 7.4.0-13)
I've compiled opencv from source by myself (not throug the javacpp-presets/opencv/cppbuild.sh) and then linked the imbs-mt library to that build. Would that be the correct way of doing it? or is that the reason for why it's not linking to the opencv preset? can i somehow check why it's trying to link to my system installed libraries instead of the ones in bytedeco ?

**Comment by saudet** [comment]
> set a breakpoint in Loader.java:796 (version 1.5.1) and see what paths are being resolved, or tried.
> 
> and aslo see line 1313 which i believe is the culprit. That nested loop there doesn't take into account duplicate subdirs.

Ah, sure, your library doesn't have a version, but it still loops over empty strings. There's some optimization that could be done around there.

> im running gcc version 7.4.0 (Debian 7.4.0-13)
> I've compiled opencv from source by myself (not throug the javacpp-presets/opencv/cppbuild.sh) and then linked the imbs-mt library to that build. Would that be the correct way of doing it? or is that 

You can use anything you want, but yes it looks like there's something wrong with your build of OpenCV. That's something you'll need to figure out on your own.

> the reason for why it's not linking to the opencv preset? can i somehow check why it's trying to link to my system installed libraries instead of the ones in bytedeco ?

Didn't you just say that you're doing just that on purpose? If you could explain what you're trying to do, I might be able to give some advice...

**Comment by netbrain** [comment]
Well, i'm simply trying to compile a native library (imbs-mt) that has a dependency on opencv. And then create a JNI for said library.

I've compiled opencv and opencv_contrib from source myself, then compiled the imbs-mt library against the opencv build.

Next i created a javacpp-preset project which generates the necessary Java JNI binding, which I then publish to my local maven repository as two jar files, one for the compiled java, and the other for the native library which contains the libjniimbs.so file.

Now my issue is that it seems to be that when i run the native code, it seems to attach a library dependency on`/usr/local/lib/libopencv_features2d.so.4.1` where as i would expect it to attach to `org.bytedeco/opencv/4.1.0-1.5.1/...../opencv-4.1.0-1.5.1-linux-x86_64-gpu.jar!/org/bytedeco/opencv/linux-x86_64-gpu/libopencv_features2d.so.4.1`

Is there some flag in javacpp other than LD_LIBRARY_PATH and java.library.path that would influence how javacpp does library loading? (i've tried changing both but behavior does not change)

Or am I missing some configuration in my mapping file? preload?

**Comment by saudet** [comment]
> Well, i'm simply trying to compile a native library (imbs-mt) that has a dependency on opencv. And then create a JNI for said library.

If that's the only thing, then use the modules for flandmark or chilitags as templates. They are pretty small (legacy) libraries that I just keep around because they don't require much maintenance, but they are good examples. Then to be sure that all libraries are compatible with your compiler, just rebuild everything with a command like `mvn install --projects .,openblas,opencv,imbs-mt`.

**Comment by netbrain** [comment]
Ok, ill look into it. Another thing, any reason why these things aren't built using dockcross? Makes it a bit easier, and more reproducible imo. to have a docker image with the build environment.

Oh and, if im building opencv with the gpu extension how would that `mvn install --projects` line look like?

**Comment by saudet** [comment]
They are built with Docker, CentOS, but it sounded like you needed Debian: https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by netbrain** [comment]
Managed to get everything up to this point. However seems to fail on locating the preset class. But everything seems correct on my end. Any tips?
```
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.5.1:parse (javacpp-parser) on project imbs-mt: Failed to execute JavaCPP Builder: org.bytedeco.imbs.presets.imbs -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.bytedeco:javacpp:1.5.1:parse (javacpp-parser) on project imbs-mt: Failed to execute JavaCPP Builder
...
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute JavaCPP Builder
...
Caused by: java.lang.ClassNotFoundException: org.bytedeco.imbs.presets.imbs
```

**Comment by saudet** [comment]
If you're not getting that with chilitags or flandmark, check for differences with those two.

**Comment by netbrain** [comment]
Im completely lost for what the issue can be.

``` diff
root@cf658f941756:/work# diff flandmark/pom.xml imbs-mt/pom.xml
13c13
<   <artifactId>flandmark</artifactId>
---
>   <artifactId>imbs-mt</artifactId>
15c15
<   <name>JavaCPP Presets for flandmark</name>
---
>   <name>JavaCPP Presets for imbs-mt</name>
18c18
<     <revision>1.07-${project.parent.version}</revision>
---
>     <revision>master-${project.parent.version}</revision>
118c107
<               <classOrPackageName>org.bytedeco.flandmark.presets.flandmark</classOrPackageName>
---
>               <classOrPackageName>org.bytedeco.imbs.presets.imbs</classOrPackageName>
124c113
<               <classOrPackageName>org.bytedeco.flandmark.**</classOrPackageName>
---
>               <classOrPackageName>org.bytedeco.imbs.**</classOrPackageName>
```

``` shell
root@cf658f941756:/work# tree flandmark/src/main/
flandmark/src/main/
|-- java
|   `-- org
|       `-- bytedeco
|           `-- flandmark
|               `-- presets
|                   `-- flandmark.java
`-- java9
    `-- module-info.java

6 directories, 2 files
root@cf658f941756:/work# tree imbs-mt/src/main/
imbs-mt/src/main/
|-- java
|   `-- org
|       `-- bytedeco
|           `-- imbs
|               `-- presets
|                   `-- imbs.java
`-- java9
    `-- module-info.java

```
``` diff
root@cf658f941756:/work# diff flandmark/platform/pom.xml imbs-mt/platform/pom.xml
14c14
<   <artifactId>flandmark-platform</artifactId>
---
>   <artifactId>imbs-mt-platform</artifactId>
16c16
<   <name>JavaCPP Presets Platform for flandmark</name>
---
>   <name>JavaCPP Presets Platform for imbs-mt</name>
19,20c19,20
<     <javacpp.moduleId>flandmark</javacpp.moduleId>
<     <revision>1.07-${project.parent.version}</revision>
---
>     <javacpp.moduleId>imbs-mt</javacpp.moduleId>
>     <revision>master-${project.parent.version}</revision>

```

**Comment by saudet** [comment]
Your class name is `Imbs`, right? It won't work if you tell it to process the non-existing class `imbs`.

**Comment by netbrain** [comment]
yes, lowercase imbs

**Comment by netbrain** [comment]
```
@Properties(
        inherit = opencv_core.class,
        value = {
                @Platform(
                        value = "windows-x86_64"
                ),
                @Platform(
                        value = "linux-x86_64"
                ),
        },
        target = "org.bytedeco.imbs",
        global = "org.bytedeco.imbs.global.imbs"
)
public class imbs implements InfoMapper {
    @Override
    public void map(InfoMap map) {
        map.put(new Info("cv::Vec3b").cast().pointerTypes("Point3i"));
    }
}

```

**Comment by saudet** [comment]
And it's getting compiled? You have an `imbs.class` somewhere in `target`?

**Comment by netbrain** [comment]
doesn't look like it :(

```
root@cf658f941756:/work# find imbs-mt/target/
imbs-mt/target/
imbs-mt/target/maven-status
imbs-mt/target/maven-status/maven-compiler-plugin
imbs-mt/target/maven-status/maven-compiler-plugin/compile
imbs-mt/target/maven-status/maven-compiler-plugin/compile/javacpp-parser
imbs-mt/target/maven-status/maven-compiler-plugin/compile/javacpp-parser/inputFiles.lst
```

**Comment by netbrain** [comment]
could it have something to do with my naming of the project with imbs-mt? instead of imbs?

**Comment by netbrain** [comment]
With debugging flag -X it all seems correct.
```
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding /work/imbs-mt/target/generated-sources/annotations to compile source roots:
  /work/imbs-mt/src/main/java
  /work/imbs-mt/src/gen/java
  /work/imbs-mt/cppbuild/linux-x86_64/java
[DEBUG] New compile source roots:
  /work/imbs-mt/src/main/java
  /work/imbs-mt/src/gen/java
  /work/imbs-mt/cppbuild/linux-x86_64/java
  /work/imbs-mt/target/generated-sources/annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO] Nothing to compile - all classes are up to date

```

**Comment by saudet** [comment]
Yeah, you'll need to set the javacpp.packageName property to get the right values in the parent pom.xml:
https://github.com/bytedeco/javacpp-presets/blob/master/mkl-dnn/pom.xml#L18

**Comment by netbrain** [comment]
yep, thats it :+1:

**Comment by netbrain** [comment]
@saudet probably not the right thread to ask this, but ill take my chances anyway :)

when compiling with  -Djavacpp.platform.extension=-gpu openblas compilation fails (i can get into the details in another issue? or would you prefer gitter/slack pm?)

should i compile openblas without the gpu extension and then other projects with it? or is it intended to be used throughout all?

**Comment by saudet** [comment]
> @saudet probably not the right thread to ask this, but ill take my chances anyway :)
> 
> when compiling with -Djavacpp.platform.extension=-gpu openblas compilation fails (i can get into the details in another issue? or would you prefer gitter/slack pm?)

The Gitter channel would be good for chatting like that yes.
 
> should i compile openblas without the gpu extension and then other projects with it? or is it intended to be used throughout all?

Yes, that's the idea. OpenBLAS doesn't have a `-gpu` build.

**Comment by saudet** [comment]
BTW, we can use AppVeyor and Travis CI to perform cross-platform builds, even on forks, by modifying the `.appveyor.yml` and `.travis.yml` files: http://bytedeco.org/builds/
