### ISSUE TITLE
How is this possible, memory corruption?

### ISSUE THREAD

**Issue by netbrain** [bytedeco/javacpp-presets#798]
Got this exception today.

```
java.lang.ArithmeticException: / by zero
	at org.bytedeco.javacv.OpenCVFrameConverter.convert(OpenCVFrameConverter.java:165)
	at org.bytedeco.javacv.OpenCVFrameConverter$ToMat.convert(OpenCVFrameConverter.java:55)
```

The failing piece of code is:
` frame.imageStride = (int)mat.step() * 8 / Math.abs(frame.imageDepth);`

Ok, so clearly `frame.imageDepth` is 0, right?

imageDepth is defined a few lines above with `frame.imageDepth = getFrameDepth(mat.depth());` which shows me the following code

(annotated with return values)
```
        switch (depth) {
            case IPL_DEPTH_8U:  case CV_8U:  return Frame.DEPTH_UBYTE; //8
            case IPL_DEPTH_8S:  case CV_8S:  return Frame.DEPTH_BYTE; //-8
            case IPL_DEPTH_16U: case CV_16U: return Frame.DEPTH_USHORT; //16
            case IPL_DEPTH_16S: case CV_16S: return Frame.DEPTH_SHORT; //-16
            case IPL_DEPTH_32F: case CV_32F: return Frame.DEPTH_FLOAT; //32
            case IPL_DEPTH_32S: case CV_32S: return Frame.DEPTH_INT; //-32
            case IPL_DEPTH_64F: case CV_64F: return Frame.DEPTH_DOUBLE; //64
            default: return -1;
        }
```

And none of these should return 0. This gives me the reason to believe that there is some sort of memory corruption going on. Suggestions?

**Comment by saudet** [comment]
We can always use something like Valgrind or Address Sanitizer for that:
https://github.com/deeplearning4j/libnd4j/wiki/Debugging-libnd4j
http://btorpey.github.io/blog/2014/03/27/using-clangs-address-sanitizer/

**Comment by saudet** [comment]
For something as simple as that though, it might be related to the order of execution of static initializers. Try not using static blocks in your code to avoid that class of issues.
