### ISSUE TITLE
Opencv Cuda warping bug

### ISSUE THREAD

**Issue by StarlightNL** [bytedeco/javacpp-presets#806]
Hello,

After compiling opencv with cuda on my devboard I've run into a problem.
The wrapper for cuda to warp mats is wrong. 
The parameters are `input(GpuMat), output(GpuMat), M(GpuMat)`
It needs to be `input(GpuMat), output(GpuMat), M(Mat)`
This is with the `warpAffine` and `warpPerspective` function

I do not know if it is with more cuda functions but I will update this issue if I encounter more errors

**Comment by saudet** [comment]
The one from the core module probably doesn't support GpuMat, that's normal. Try the one from the cudawarping module.

**Comment by StarlightNL** [comment]
I tested the new build but could not start it. I do not know if I should report it here or in another issue. When starting I get the following error
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1058)
	at nl.ideax.farmbot.camera.Main.main(Main.java:54)
Caused by: java.lang.UnsatisfiedLinkError: no quadmath in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1143)
	... 7 more
```

I tried building openblas but that failed as well.
The board that I use now is a Nvidia Jetson AGX Xavier

**Comment by saudet** [comment]
I'm pretty sure it works, see issue #735. What does it look like with the system property "org.bytedeco.javacpp.logger.debug" set to "true"?

**Comment by StarlightNL** [comment]
With debug on I get the following
```
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading class org.bytedeco.openblas.global.openblas_nolapack
Loading library gcc_s
Failed to load for gcc_s@.1: java.lang.UnsatisfiedLinkError: no gcc_s in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading library quadmath
Failed to load for quadmath@.0: java.lang.UnsatisfiedLinkError: no quadmath in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Loading /usr/lib/aarch64-linux-gnu/libgfortran.so
Loading /usr/lib/aarch64-linux-gnu/libgfortran.so.4
Loading /usr/lib/aarch64-linux-gnu/libgfortran.so
Loading /root/.javacpp/cache/aarch64-linux-gnu/libopenblas_nolapack.so.0
Loading library jniopenblas_nolapack
Failed to load for jniopenblas_nolapack: java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1058)
	at nl.ideax.farmbot.camera.Main.main(Main.java:54)
Caused by: java.lang.UnsatisfiedLinkError: no quadmath in java.library.path: [., /usr/local/cuda-10.0/lib64, /usr/local/lib, /home/farmbot/sourcebuilding/javacpp-presets-ci, /home/farmbot/sourcebuilding/javacpp-presets-ci/opencv/cppbuild/linux-arm64-gpu/lib, /usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1143)
	... 7 more
```

**Comment by saudet** [comment]
Looks like `/root/.javacpp/cache/aarch64-linux-gnu/libopenblas_nolapack.so.0` isn't loading for some reason but JavaCPP isn't guessing right. What does `ldd` say on that file?

**Comment by saudet** [comment]
Actually that file most likely doesn't exist. The JAR files for OpenBLAS are probably just missing from the class path. If you're not using Maven, make sure you have everything it needs.

**Comment by StarlightNL** [comment]
The problem with OpenBLAS is fixed. Seems that maven didn't like to add the platform compiled jar to the classpath.

The other problems with the warp functions is solved.

Thanks for the quick responses.
