### ISSUE TITLE
OpenCV Unsatisfied Link 

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacpp-presets#829]
I'm using version 1.5.2 use the command Loader.load(opencv_java.class); to load the OpenCV dlls. 
but giving me error. 

> Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no opencv_java412 in java.library.path: [C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin/client, C:/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp, C:\Python35\, C:\Python35\Scripts\, C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Maven\bin, C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Users\Admin\AppData\Local\Microsoft\WindowsApps, ., C:\Users\Admin\AppData\Local\Programs\EmEditor, C:\Program Files (x86)\Jar2Exe Wizard\, C:\Users\Admin\eclipse-NEWCODE\java-2019-09\eclipse, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at image.viewer/com.imviewer.panes.Test$1.run(Test.java:21)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by saudet** [comment]
The presets contain no reference to "opencv_java412". You're probably trying to use something else that isn't related?

**Comment by AKMANSoft** [comment]
Sorry the above error occurred when I try to load the run the command: `System.loadLibrary(Core.NATIVE_LIBRARY_NAME);` 

so I change the command then I get this error.: `Loader.load(opencv_java.class);` then I start getting this error, basically Im trying to load the OpenCV dlls. 

`Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: [C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin/client, C:/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp, C:\Python35\, C:\Python35\Scripts\, C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Maven\bin, C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Users\Admin\AppData\Local\Microsoft\WindowsApps, ., C:\Users\Admin\AppData\Local\Programs\EmEditor, C:\Program Files (x86)\Jar2Exe Wizard\, C:\Users\Admin\eclipse-NEWCODE\java-2019-09\eclipse, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.load(Loader.java:1192)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.openblas/org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:10)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.load(Loader.java:1058)
	at image.viewer/com.imviewer.panes.Test$1.run(Test.java:19)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.UnsatisfiedLinkError: no openblas_nolapack in java.library.path: [C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin/client, C:/Program Files/AdoptOpenJDK/jdk-11.0.4.11-hotspot/bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp, C:\Python35\, C:\Python35\Scripts\, C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Maven\bin, C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Users\Admin\AppData\Local\Microsoft\WindowsApps, ., C:\Users\Admin\AppData\Local\Programs\EmEditor, C:\Program Files (x86)\Jar2Exe Wizard\, C:\Users\Admin\eclipse-NEWCODE\java-2019-09\eclipse, ., .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
	at java.base/java.lang.System.loadLibrary(System.java:1867)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1543)
	at org.bytedeco.javacpp/org.bytedeco.javacpp.Loader.load(Loader.java:1143)
	... 20 more
`

**Comment by saudet** [comment]
OpenCV needs OpenBLAS. Make sure you have the JAR files for OpenBLAS as well in the class path.

**Comment by AKMANSoft** [comment]
Thank you it resolve the issue, before I added Javacv and it was showing all jars in the maven libraries, when I explicitly add the OpenCV and OpenBLAS jar, it resolve the issue.
