### ISSUE TITLE
running cudnn on windows?

### ISSUE THREAD

**Issue by janblok** [bytedeco/javacpp-presets#83]
After reading the sample usage at:
https://github.com/bytedeco/javacpp-presets/tree/master/cuda#sample-usage
I did exactly these 3 steps, create pom.xml and Java source file, follow by executing maven, I get the exception below.
Now I wonder did I miss-read the sample usage and I DO have to compile native windows binaries?

--------------
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: no jnicudnn in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:550)
        at org.bytedeco.javacpp.Loader.load(Loader.java:415)
        at org.bytedeco.javacpp.Loader.load(Loader.java:358)
        at org.bytedeco.javacpp.cudnn.<clinit>(cudnn.java:12)
        at MNISTCUDNN$network_t.createHandles(MNISTCUDNN.java:147)
        at MNISTCUDNN$network_t.<init>(MNISTCUDNN.java:170)
        at MNISTCUDNN.main(MNISTCUDNN.java:465)
        ... 6 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\jblok\AppData\Local\Temp\jav
acpp1219488325733408\jnicudnn.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:539)
        ... 12 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.617 s

**Comment by saudet** [comment]
There's no build for Windows yet. If you could contribute one, it would be
most welcome! Thanks

**Comment by saudet** [comment]
Oops, I misread your question. Yes Windows works, but we need to put the
DLLs NVIDIA gives you in your system path somewhere anywhere. That isn't
part of the presets.

**Comment by janblok** [comment]
But they are on my path! I can run deeplearning4j.org (which also requires them) without problems.
Also I can run "cudafe.exe" in any folder at cmdline, so the cuda 7.x stuff is for sure in my path.

Please advice

**Comment by saudet** [comment]
What about cudnn64_65.dll? Where did you put that one?

**Comment by janblok** [comment]
I was under the impression cudnn is part of nvidia cuda toolkit to my suprise its not.
Would be very useful if the exception told the dll name its missing.
Thanks for helping out!

**Comment by saudet** [comment]
That's a problem with Windows. Please report to Microsoft :)

**Comment by jitterhorse** [comment]
Where should cudnn*_*.dll be? 

I put it in the Folders that are mentioned in the installation instructions here: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html

But i think I also get java.lang.UnsatisfiedLinkError due to missing cudnn libraries. But I can't say for sure because I only get in the Error Message in Eclipse:

jniopencv_cudaobjdetect.dll: Can't find dependent libraries

when trying to init a CudaCascadeClassifier.

**Comment by saudet** [comment]
All CUDA libraries including cuDNN are now bundled in the "redist" artifacts:
https://github.com/bytedeco/javacpp-presets/tree/master/cuda
Enjoy!

**Comment by jitterhorse** [comment]
Very nice! Thank you!
