### ISSUE TITLE
Linking problems in currently nightly

### ISSUE THREAD

**Issue by frankier** [bytedeco/javacpp-presets#922]
Libraries that have been linked at compile time and packaged into the jar are not longer being found.

```
Exception in thread "pool-3-thread-2" java.lang.UnsatisfiedLinkError: no jniopenpose in java.library.path: [/usr/local/lib, /usr/local/lib/x86_64-linux-gnu/, ., /usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2680)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.openpose.global.openpose.<clinit>(openpose.java:30)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.openpose.OpWrapper.<clinit>(OpWrapper.java:46)
[...]
Caused by: java.lang.UnsatisfiedLinkError: /home/frankier/.javacpp/cache/cineast-api-2.5-full.jar/org/bytedeco/openpose/linux-x86_64/libjniopenpose.so: libopenpose_hand.so: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
	at java.base/java.lang.Runtime.load0(Runtime.java:745)
	at java.base/java.lang.System.load(System.java:1871)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1633)
	... 16 more
```

So it looks like libjniopenpose.so is loaded, but the linked library libopenpose_hand.so cannot be found. However, it's right there in the cache directory:

```
$ ls /home/frankier/.javacpp/cache/cineast-api-2.5-full.jar/org/bytedeco/openpose/linux-x86_64/
libcaffe.so.1.0.0         libopencv_imgcodecs.so.4.3  libopenpose_hand.so
libgcc_s.so.1             libopencv_imgcodecs.so.4.4  libopenpose_net.so
libgfortran.so.4          libopencv_imgproc.so.4.3    libopenpose_pose.so
libhdf5_cpp.so.200        libopencv_imgproc.so.4.4    libopenpose_producer.so
libhdf5_hl_cpp.so.200     libopencv_videoio.so.4.3    libopenpose.so
libhdf5_hl.so.200         libopencv_videoio.so.4.4    libopenpose.so.1.6.0
libhdf5.so.200            libopenpose_3d.so           libopenpose_thread.so
libjniopenpose.so         libopenpose_calibration.so  libopenpose_tracking.so
libopenblas.so.0          libopenpose_core.so         libopenpose_unity.so
libopencv_core.so.4.3     libopenpose_face.so         libopenpose_utilities.so
libopencv_core.so.4.4     libopenpose_filestream.so   libopenpose_wrapper.so
libopencv_highgui.so.4.3  libopenpose_gpu.so          libquadmath.so.0
libopencv_highgui.so.4.4  libopenpose_gui.so
```

**Comment by saudet** [comment]
It might not be compatible with OpenCV 4.4.0, make sure it's supposed to work.

**Comment by saudet** [comment]
It loads fine for me. Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" and let me know what gets displayed on the console when you try to run the sample.

**Comment by saudet** [comment]
Please let me know if you are still having problems with this! We'll probably be making a release sometime next month...

**Comment by frankier** [comment]
Yes sorry it seems to work now. Not sure what the problem was exactly. I would suppose it was something to do with a transitive dependency somehow...
