### ISSUE TITLE
Caffe preset build: Missing dependency org.bytedeco:javacpp:1.1-SNAPSHOT

### ISSUE THREAD

**Issue by sebastianlutter** [bytedeco/javacpp-presets#96]
I try to build the native libs of javacpp caffe preset  for Ubuntu 14.04 on x86_64 (the ones provides on mvn repo are build against fedora 21 as far as I know and do not work on Ubuntu 14.04).

I cloned https://github.com/bytedeco/javacpp-presets and tried to build it:
> mvn clean && mvn -U install --projects .,caffe -X

It failed with error:
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] JavaCPP Presets ................................... SUCCESS [0.519s]
> [INFO] JavaCPP Presets for OpenCV ........................ FAILURE [0.028s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.207s
> [INFO] Finished at: Tue Oct 06 16:26:44 CEST 2015
> [INFO] Final Memory: 18M/375M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Plugin org.bytedeco:javacpp:1.1-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.bytedeco:javacpp:jar:1.1-SNAPSHOT: Could not find artifact org.bytedeco:javacpp:pom:1.1-SNAPSHOT -> [Help 1]
> org.apache.maven.plugin.PluginResolutionException: Plugin org.bytedeco:javacpp:1.1-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.bytedeco:javacpp:jar:1.1-SNAPSHOT
>        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:129)
 >       at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:142)
 >       at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:261)
>        at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:185)

When I try to build another project (i.e. opencv) the same error appears.

Where can I get the mentioned version? Thanks or any hint.

**Comment by sebastianlutter** [comment]
Solved it myself. 

* checkout javacpp project
* build and install it using mvn install --projects .,caffe
