### ISSUE TITLE
JavacppLoader,failedtoloadffmpegclass

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [bytedeco/javacpp-presets#993]
Did this:
System.out.println("try load");
String ffmpeg = org.bytedeco.javacpp.Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
System.out.println(ffmpeg);

Console out:
try load
Warning: Version of org.bytedeco:ffmpeg could not be found.

Expected out:
try load
Warning: Version of org.bytedeco:ffmpeg could not be found.
ffmpegpath?

Dep setup check:
org.bytedeco.javacpp.ok
org.bytedeco.javacpp\windows-x86_64.ok
org\bytedeco\ffmpeg.ok
org\bytedeco\ffmpeg\windows-x86.ok

org\bytedeco\javacv.ok(used in the subsequent functions statement,possibly unrelated)
org\bytedeco\opencv.ok(used in the subsequent functions statement,possibly unrelated)
org\bytedeco\opencv\windows-x86_64.ok(used in the subsequent functions statement,possibly unrelated)

Anyone have this problem?

**Comment by xwaeaewcrhomesysplug** [comment]
sadly still same,from https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5.5-SNAPSHOT/

javacpp-1.5.5-20210104.082409-576.jar
javacpp-1.5.5-20210104.082531-578-windows-x86_64.jar
ffmpeg-4.3.1-1.5.5-20201207.134112-723.jar
ffmpeg-4.3.1-1.5.5-20201207.134112-723-windows-x86.jar

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information.

**Comment by xwaeaewcrhomesysplug** [comment]
sorry,is that by maven or gradle?Any refereable examples in terminal?My project currently does not use maven.I am testing stuffs.
Thank you very much.

**Comment by saudet** [comment]
Either, it doesn't matter. Just set the system property.

**Comment by saudet** [comment]
> javacpp-1.5.5-20210104.082409-576.jar
> javacpp-1.5.5-20210104.082531-578-windows-x86_64.jar
> ffmpeg-4.3.1-1.5.5-20201207.134112-723.jar
> ffmpeg-4.3.1-1.5.5-20201207.134112-723-windows-x86.jar

You'll need to have the binaries for windows-x86_64 in your class path for this to work.

**Comment by xwaeaewcrhomesysplug** [comment]
Thanks i found the error.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path: F:\ProgramSetup\Codercsbackup\Java tools\openjdk\referenceimplementation\jdk-15\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;F:\ProgramSetup\Codercsbackup\Java tools\openjdk\referenceimplementation\jdk-15\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;;C:\Program Files (x86)\gnupg\bin;.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
        at java.base/java.lang.System.loadLibrary(System.java:1893)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
        at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:468)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1139)

AH,sorry I will add it now and try runnning again

**Comment by xwaeaewcrhomesysplug** [comment]
ok changed the binaries.
ffmpeg-4.3.1-1.5.4.jar
ffmpeg-4.3.1-1.5.5-20210108.181347-775-windows-x86_64

output:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnipostproc in java.library.path: F:\ProgramSetup\Codercsbackup\Java tools\openjdk\referenceimplementation\jdk-15\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;F:\ProgramSetup\Codercsbackup\Java tools\openjdk\referenceimplementation\jdk-15\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;;C:\Program Files (x86)\gnupg\bin;.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
        at java.base/java.lang.System.loadLibrary(System.java:1893)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
        at org.bytedeco.ffmpeg.global.postproc.<clinit>(postproc.java:16)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:468)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
```

**Comment by saudet** [comment]
This works just fine for me on Windows for me:
```java
        String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
        ProcessBuilder pb = new ProcessBuilder(ffmpeg, ...);
```

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --prefix=.. --disable-iconv --disable-opencl --disable-sdl2 --disable-bzlib --disable-lzma --disable-linux-perf --enable-shared --enable-version3 --enable-runtime-cpudetect --enable-zlib --enable-libmp3lame --enable-libspeex --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-openssl --enable-libopenh264 --enable-libvpx --enable-libfreetype --enable-libopus --enable-cuda --enable-cuvid --enable-nvenc --enable-libmfx --enable-w32threads --enable-indev=dshow --target-os=mingw32 --cc='gcc -m64' --extra-cflags=-I../include/ --extra-ldflags=-L../lib/ --extra-libs='-static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lgcc_eh -lWs2_32 -lcrypt32 -lpthread -lz -lm -Wl,-Bdynamic'
```

**Comment by xwaeaewcrhomesysplug** [comment]
huh,this is interesting probably my own classpath or setup have some problem.lol.Not the present problem then,I am going to just simply close this issue then.

**Comment by saudet** [comment]
Let us know if you figure it out!
